### ISSUE TITLE
Sync Table with UXPin

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#1053]
Changes:

- Thicker border between TableHeader / TableBody (vertical and horizontal) for bordered variant
- Fix the sizing of the sort iconography (when sorted, the icon is slightly displaced)
- For sortable table headers, change the icon from `space-between` to `flex-start`
- Update sort up / down icon so it's not as large and matches UXPin
- Add a note to documentation to recommend that authors indicate the current sorted column by default:
  - > As a best practice, when a table has sorted columns an author should indicate which column is currently sorted by setting the sort direction for the active sorted column.

UXPin Design System: https://app.uxpin.com/design-system/c933c74928e2195cc540/ui-patterns/213536

**Comment by bobbyomari** [comment]
This has been completed and is part of #1154
