### ISSUE TITLE
Combobox Component (Single Select)

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#1088]
Follow general ARIA practices guidelines: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/

This implementation addresses only single select comboboxes.

- for multiselect see #1103.
- for custom form values see #1184 

List items can be provided via a child component, `ComboboxOption`:

```jsx
<Combobox label="Combobox">
  <ComboboxOption value="...">
    Item
    Longer Description
  </ComboboxOption>
</Combobox>
```

...or via a list with item definition:

```jsx
<Combobox label="Combobox" options={[{ label: 'Foo', value: 'foo' }]} />
```

The label provided for Combobox should be of type [`ContentNode`](https://github.com/dequelabs/cauldron/blob/d9725cdd30faf9005ac53809d829e5b80c8983e8/packages/react/src/types.ts#L14-L19) to allow for additional values beyond strings:

```jsx
<Combobox label={`<Icon type="apple"/> Fruit`}>
  ...
</Combobox>
```

To allow for grouping of items, an additional `ComboboxGroup` component can be used to wrap combobox items:

```jsx
<Combobox label="Combobox">
  <ComboboxGroup label="Group A">
   <ComboboxItem>1</ComboboxItem>
   <ComboboxItem>2</ComboboxItem>
   <ComboboxItem>3</ComboboxItem>
  </ComboboxGroup>
  <ComboboxGroup label="Group B">
   <ComboboxItem>4</ComboboxItem>
   <ComboboxItem>5</ComboboxItem>
   <ComboboxItem>6</ComboboxItem>
  </ComboboxGroup>
</Combobox>
```

For the list of items and `ComboboxOption`, providing the `value` property is optional and will reflect the value of the label associated with that item. Additionally, a `selected` prop can be provided to both to indicate that item is currently selected.

Under the hood:

- The input component should behave similarly to `<TextField />` (some different accommodations may need to be made to help support #1103)
  - Include inner right padding to prevent text overflowing the down arrow
  - General input props should be supported such as `disabled`, `required`, etc.
- Use the same styles as `<OptionsMenuList>` to display the list of items
- Allow custom filtering function to display matching items on input via prop 
  - Defaults to a text matching based on the the value or label of the item
- Support both auto selection and manual selection during autocomplete (see `#2` and `#3` list items in the autocomplete section of the aria authoring practices)
- When selected, an item should show it's selected state in the popup
  - This checkbox can reuse the existing `check` icon with a css ring to match the design 
  - Changing the selected item(s) will call any `onChange` handlers

Other Notes:

Opening/closing the listbox has the following behaviors:

- When Open
    - Has Selected Value (Autocomplete Manual)
        - The input value will be set to an empty string to allow users to see all options and filter options based on the combobox input
    - No Selected Value (Autocomplete Manual)
        - The input value will retain its initial value and will not clear, allowing the user to update the combobox input to change the filtered options 
- When Closed
    - Has Selected Value (Autocomplete Manual)
        - If the selected value did not change, the combobox input will revert back to the selected value 
    - No Selected Value (Autocomplete Manual)
        - The combobox input will retain the currently typed characters
 
Examples: 

![light/dark versions of combobox](https://github.com/dequelabs/cauldron/assets/1062039/64dabb55-1fd5-4bfd-bef8-f1c6ab360e32)

- [Overall UX design](https://preview.uxpin.com/520e80315786a67ba43a3ca50598e6d69782627c#/pages/163502797?mode=cvidm)
- [Additional Combobox Examples](https://preview.uxpin.com/520e80315786a67ba43a3ca50598e6d69782627c#/pages/163348083/simulate/no-panels?mode=cvim)

**Comment by thuey** [comment]
> To allow for grouping of items, an additional ComboboxGroup component can be used to wrap combobox items:

Is there a similar way to accomplish this using the item definition list approach?

As an aside, what is the value in supporting two ways to define the list?

**Comment by scurker** [comment]
> As an aside, what is the value in supporting two ways to define the list?

It's similar to how we support `options` and `HTMLOptions` for selects and there's some value in keeping the props similar to make it easy to convert between the two:

https://github.com/dequelabs/cauldron/blob/b60588fe44708a3fc01fb8bf18866171a8e0d9b3/packages/react/src/components/Select/index.tsx#L19-L20

The general idea is if an author needs a simple list of label/value items they can use the list array. More advanced configurations could use the component to display more complex items.

As an example, [React Spectrum (Adobe) Combobox](https://react-spectrum.adobe.com/react-spectrum/ComboBox.html) does something very similar.

> Is there a similar way to accomplish this using the item definition list approach?

Not unless we really think it's needed. I'm double checking with @dequelabs/cauldron-design on this, but my understanding is most cases will not need to be grouped so the list format will be the easiest to implement.

**Comment by schne324** [comment]
> `<ComboboxGroup label="Group A">`

This may already be planned (perhaps some prop types defined in the ticket would've cleared this up a bit) but I think the `label` prop for `ComboboxGroup` should support any react nodes so we can do stuffs like 

```jsx
<ComboboxGroup label={<Icon type="bananas" /> Fruits}>
   <ComboboxItem>Bananas</ComboboxItem>
   <ComboboxItem>Mangos</ComboboxItem>
   <ComboboxItem>Cucumbers (yes a cucumber is in fact a fruit)</ComboboxItem>
</ComboboxGroup>
```

---

Due to the complicated nature of comboboxes (and historical UA/AT bugs surrounding comboboxes), it may be useful to clearly document which screen readers we will support for this (in both the ticket and demo/docs page for it). I would suggest latest VO, NVDA, and JAWS versions as our target support here but maybe that is something to consider more "globally" (on the cauldron readme/landing page of docs list what AT we support)

**Comment by scurker** [comment]
> > `<ComboboxGroup label="Group A">`
> 
> This may already be planned (perhaps some prop types defined in the ticket would've cleared this up a bit) but I think the `label` prop for `ComboboxGroup` should support any react nodes so we can do stuffs like

Good callout, I can update the description. 

> ```js
> <ComboboxGroup label={<Icon type="bananas" /> Fruits}>
>    <ComboboxItem>Bananas</ComboboxItem>
>    <ComboboxItem>Mangos</ComboboxItem>
>    <ComboboxItem>Cucumbers (yes a cucumber is in fact a fruit)</ComboboxItem>
> </ComboboxGroup>
> ```
> 
> Due to the complicated nature of comboboxes (and historical UA/AT bugs surrounding comboboxes), it may be useful to clearly document which screen readers we will support for this (in both the ticket and demo/docs page for it). I would suggest latest VO, NVDA, and JAWS versions as our target support here but maybe that is something to consider more "globally" (on the cauldron readme/landing page of docs list what AT we support)

There's already general guidelines here: https://cauldron.dequelabs.com/component-guidelines#accessibility

**Comment by Amandeque** [comment]
Estimates: 
SIZE: Large

**Comment by Keerthi-Penukonda** [comment]
## Question

@scurker error message is being displayed even when selected an option from "Does this combobox have an error?" dropdown. Is this expected? or do we need to remove the error once the option is selected?

![image](https://github.com/dequelabs/cauldron/assets/40262884/34794546-0383-49dc-ac5c-947d41f637fb)

## Testing
Verified UI and performed basic accessibility testing. Did not find any issues. Moving this to ally column for accessibility testing.

**Comment by scurker** [comment]
@Keerthi-Penukonda Yes, that's expected. Combobo/text fields are dependent on the author clearing the error once there's a valid selection made.

**Comment by scurker** [comment]
Thanks @VaniChinnam, I've raised issues for the following:

- [1505025](https://axeauditor.dequecloud.com/test-run/87ff92fc-25f1-11ee-a855-1b2298d1b894/issue/c5cc4b1c-5886-11ee-9399-9336eb8a0144?sortField=ordinal&sortDir=asc&filter%5Brule%5D=manual&filter%5Bpage_number%5D=49&row=0): #1201 
- [1495130](https://axeauditor.dequecloud.com/test-run/87ff92fc-25f1-11ee-a855-1b2298d1b894/issue/98b155e6-512e-11ee-b2ae-1b13575e65cf?sortField=ordinal&sortDir=asc&filter%5Brule%5D=manual&filter%5Bpage_number%5D=49&row=0): #1202 
- [1505019](https://axeauditor.dequecloud.com/test-run/87ff92fc-25f1-11ee-a855-1b2298d1b894/issue/60646e32-5884-11ee-be02-0f9218df4b24?sortField=ordinal&sortDir=asc&filter%5Brule%5D=manual&filter%5Bpage_number%5D=49&row=0): #1203

For [1505022](https://axeauditor.dequecloud.com/test-run/87ff92fc-25f1-11ee-a855-1b2298d1b894/issue/b53f6028-5885-11ee-80b7-cfc6e26c8fe7?sortField=ordinal&sortDir=asc&filter%5Brule%5D=manual&filter%5Bpage_number%5D=49&row=0), it was an intentional design decision to allow for a user to easily filter down the list of options again if the user expanded the list again without being limited to options that were currently there. If the user types/remove characters the value does persist (or gets restored to its original value if no selections were made). I can ask @dequelabs/cauldron-design to see if we can get some usability testing here to see if this is something we want to tweak.

**Comment by Keerthi-Penukonda** [comment]
Closing this ticket as we have separate tickets to track accessibility issues.
