### ISSUE TITLE
Bug: Text-field overflows its container

### ISSUE THREAD

**Issue by yhafez** [dequelabs/cauldron#1138]
### Steps to reproduce

Steps to reproduce

Find a text field in a sufficiently narrow container, such as that in `/signup`. Increase zoom to 200% and shrink viewport width.

### Expected Behavior

Text-field shrinks to fit enclosing container.

### Actual Behavior

Text-field overflows out of container as a result of its [min-width property](https://github.com/dequelabs/cauldron/blob/82de49c0307ba11266fe348884852b039e3ead9b/packages/styles/forms.css#L313).

### Version

5.6.2

### What browsers are you experiencing the problem on?

Chrome

### Anything else we should know?

Additional information

Screenshot:
![Screenshot 2023-07-29 at 6 32 05 PM](https://github.com/dequelabs/cauldron/assets/60084578/a1dc6baf-7d9f-4a66-81a3-c0bcfc4fa26c)

**Comment by scurker** [comment]
The solution here should constrain the width property of `TextField`:

```css
min-width: min(var(--input-min-width), 100%);
```
