### ISSUE TITLE
Add copy functionality to Code component

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#1140]
![screenshot of code component from figma](https://github.com/user-attachments/assets/e0979d74-55ef-4427-9eb8-d8d4d9462a41)

This has a dependency on #970 and #1193

This is an extension to the existing `Code` component to allow a "copy" button to be included with each block along with an optional label.

## Interface

```ts
type CodeProps = {
  children: string;
  language?: 'javascript' | 'css' | 'html' | 'yaml';
  className?: string;
  scrollable?: boolean;
  label?: ContentNode;
  allowCopy?: boolean;
  copyButtonProps?: React.ComponentProps<CopyButton>;
} & SyntaxHighlighterProps &
  React.HTMLAttributes<HTMLDivElement>
```

The major changes are the addition of props to support copy:

- `label` - The name for the code block which would be `aria-describedby` its label (if it exists)
- `allowCopy` - prop to indicate copy button is available
- `copyButtonProps` - prop to set individual properties specific to `CopyButton`

Example:

```jsx
<Code language="css" allowCopy copyButtonProps={{ children: 'Copy element source' }}>
.foo {
  color: blue;
}
</Code>
```

**Comment by stephenmathieson** [comment]
There are currently ~9k different implementations of this throughout our codebases. It'll be great when we can leverage this from Cauldron!
