### ISSUE TITLE
Add 4-scale `ImpactBadge` Component

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#1141]
`ImpactBadge` is an extension of the [`Badge` component](https://github.com/dequelabs/cauldron/issues/1590) with more defined requirements.

## Design Specs

![impact badge with default and small sizes](https://github.com/user-attachments/assets/bae00297-4988-472f-9fa7-6e20549982af)

![impact badge anatomy](https://github.com/user-attachments/assets/658b3d88-ae4e-44ea-87ce-f24a96dfb480)

`ImpactBadge` is a primitive component to display various impact levels with an associated icon/background color:

- Critical
  - Icon: `chevron-double-up`
  - Background Color: `#fea7a6` (new global variable `--accent-error-active`, mapped from `--issue-critical`)
  - Border Color: `#db6379` (currently `--accent-error-disabled`)
- Serious
  - Icon: `chevron-up`
  - Background Color: `--accent-caution` (mapped from `--issue-serious`)
  - Border Color: `--accent-warning` 
- Moderate
  - Icon: `chevron-down`
  - Background Color: `#f0c4f8` (mapped from `--issue-moderate`)
  - Border Color: `#eb94ff` (doesn't exist in Cauldron, use as one-off)
- Minor
  - Icon: `chevron-double-down`
  - Background Color: `--gray-20` (mapped from `--issue-minor`)
  - Border Color: `--gray-30` 

The badge itself should have a minimum height of `24px` using `--target-size-minimum` for the small size. The icon should have roughly `1px` spacing on the horizontal axis, with the text having a right spacing of `--space-smaller`.

The `default` size should match the height of buttons, which is currently `36px`.

The text color of the labels should always be set to `--gray-90`.

## Interface

```ts
interface ImpactBadge extends Badge {
  type: 'critical' | 'serious' | 'moderate' | 'minor'
  label?: ContentNode
}
```

> [!NOTE]
> Cauldron should have a default label for each impact type in order to provide an accessible name by default, but still allow content authors to provide an alternative label for translation purposes.

## Example:

```jsx
<ImpactBadge type="critical" />
```

If you need access to the designs, please reach out to a member of the Cauldron team.

**Comment by scurker** [comment]
Investigate different sizing (e.g. smaller icons potentially) as an alternate variant.

**Comment by shawnsharpDQ** [comment]
4 sizes (XL, L, M, S). Labels are not required. Can be paired with a label, link, or left standalone. 
 
[UXPin](https://preview.uxpin.com/b5da4589206f4e648476e27134f500feb492a830#/pages/164153495?mode=vidm)

Still needs to be added to UXPin Cauldron Components.

**Comment by anastasialanz** [comment]
@shawnsharpDQ @scurker and I chatted about setting this icon size to 13x13 and letting users set a larger icon size if necessary. Down the road, if we decide that we should support multiple sizes of this icon, we can add the prop to handle sizing.

**Comment by anastasialanz** [comment]
What does "Size: 10" mean?

**Comment by scurker** [comment]
> What does "Size: 10" mean?

The icon size in Figma is 10px, where Cauldron's viewbox for icons is a bit larger - I tried to translate that as best I could from the Figma design to the implementation and the following graphic should be a good visual representation of the structure:

![image](https://github.com/dequelabs/cauldron/assets/1062039/128e68d3-ccc4-4dd2-8b6b-4dd60b63618e)

**Comment by anastasialanz** [comment]
Would this be a new page in the docs?

**Comment by scurker** [comment]
Yes, this should have a new docs page documenting the component
