### ISSUE TITLE
Create TagButton component for light and dark theme

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#1161]
This is an extension of the existing `<Button variant="tag">` that requires specific properties to help indicate its interactiveness.

UXPin Component (light): https://preview.uxpin.com/design-system/c933c74928e2195cc540/6769360,light-tag-actionable

![Image](https://user-images.githubusercontent.com/28606186/259433235-1b8de1ef-cca4-4a86-ab81-4ecd5d6c5429.png)

UXPin Component (dark): https://preview.uxpin.com/design-system/c933c74928e2195cc540/6771812,dark-tag-actionable

![Image](https://user-images.githubusercontent.com/28606186/259433132-c47003f8-5d1a-4f34-9c1b-d0e4ce83ea8e.png)

### Configurable: 

- Label
- Value
- Icon
- Action (link to external URL, open things, remove things, etc.) 

The disabled state is not implicitly supported, the author should instead use `Tag` in absence of the disabled state.

**Comment by longmatthewh** [comment]
@scurker will there be a couple variants for this—one that's an `<a>`, and one that's a `<button>`?

**Comment by scurker** [comment]
There shouldn't be other variants, but if we can allow the component to be polymorphic if it needs to be, defaulting to `button`. There's an example of that with [IconButton](https://github.com/dequelabs/cauldron/blob/4d292274916c7399fd2b9ccc4daf6ca7d1968432/packages/react/src/components/IconButton/index.tsx#L31-L34).
