### ISSUE TITLE
Combobox Hidden Form Values

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#1184]
see #1088 for initial implementation

Comboboxes typically have an input value and a label value, which are not necessarily the same. Authors may want to have a value that is different from both when the input gets submitted via a form.

To support opaque or hidden form values, a `formValue` property will be added to Combobox to support this capability.

## Via Combobox Children:

```jsx
<Combobox name="fruit" value="Apple">
  <ComboboxOption key="123" value="Apple" formValue="123">🍎 Apple</ComboboxOption>
  <ComboboxOption key="456" value="Banana" formValue="456">🍌 Banana</ComboboxOption>
  <ComboboxOption key="789" value="Cucumber" formValue="789">🥒 Cucumber</ComboboxOption>
</Combobox>
```

## Via Combobox Options:

```jsx
function ComboboxFormValues() {
  const options = [
    { key: 123, label: 'Apple', formValue: '123' },
    { key: 456, label: 'Banana', formValue: '456' },
    { key: 789, label: 'Cucumber', formValue: '789' }
  ]
  return <Combobox name="fruit" value="Apple" options={options} />
}
```

When `name` is set, a hidden input field will be rendered with the name prop that will have its value set to the `formValue` of the currently selected combobox option. When `formValue` is omitted or not set for the selected combobox option, the value of the hidden input will default to the set `value` or the inner text contents of the selected combobox option.

**Comment by thuey** [comment]
> When both `name` and `formValue` is set, a hidden input field will be rendered with that name that will get set to the selected property key value of the combobox options.

A few questions:

1. Did you mean `formKey` here?
2. When you say "will be rendered with that name", are you referring to the value of `formValue`/`formKey`?
3. I'm curious why you went with this `formKey` approach, as opposed to the `formValue` approach you mentioned here: https://github.com/dequelabs/cauldron/pull/1180#discussion_r1310854160?

**Comment by scurker** [comment]
> 1. Did you mean `formKey` here?

Yeah, typo when updating.

> 2. When you say "will be rendered with that name", are you referring to the value of `formValue`/`formKey`?

Reworded to try and clarify.

> 3. I'm curious why you went with this `formKey` approach, as opposed to the `formValue` approach you mentioned here: [feat(react): add Combobox component #1180 (comment)](https://github.com/dequelabs/cauldron/pull/1180#discussion_r1310854160)?

I initially went with the `formValue` approach because that's what React spectrum was doing, but after further consideration I felt that `formKey` felt more appropriate.

I felt like `formKey` was more descriptive of its purpose, and specifying that you're passing in the key and not the value felt like it aligned a little bit better. I wouldn't want someone to accidentally pass in some value expecting that value to be submitted to the form as opposed to the value of the key.

**Comment by scurker** [comment]
The following hidden input would be rendered based on your above example when "Apple" is selected:

```tsx
<input type="hidden" name="fruit" value="123" />
```

If the desired behavior is for "Apple" to be sent to the server, the author could set `formKey` as `formKey="value"` or omit that prop entirely.

**Comment by thuey** [comment]
Gotcha. I think part of the confusion for me is that it is unclear what "key" refers to in this context, or conceptually, what a "form key" is. In my head, "key" is getting conflated with a `React` key used for uniqueness and a form field "name". Based on your example, "form key" does not seem to directly refer to either of these.

Instead, the approach seems like the `formValue` approach, but you're able to customize what property is looked at in order to derive the `formValue`. For example, this would effectively be `formValue`:

```tsx
<Combobox name="fruit" formKey="formValue">
  <ComboboxOption formValue="123" value="Apple">🍎 Apple</ComboboxOption>
  <ComboboxOption formValue="456" value="Banana">🍌 Banana</ComboboxOption>
  <ComboboxOption formValue="789" value="Cucumber">🥒 Cucumber</ComboboxOption>
</Combobox>
```

But it might be helpful for other devs to take a look at the proposed API, since it could just be me that's struggling with the concepts.

**Comment by scurker** [comment]
> Instead, the approach seems like the formValue approach, but you're able to customize what property is looked at in order to derive the formValue. For example, this would effectively be formValue:

Yeah the approach is the same, I just thought that the prop being named `formKey` instead of `formValue` would make its intended usage more clear. You are specifying the lookup key to be used when determining the form value.

I want to find the approach that makes the most sense from a surface level, so I think it would be good to get others to weigh in here.

**Comment by JoshMK** [comment]
This is looking super solid. I only have one suggested change.

Since we're announcing 'selected' for items when using a screen reader and not relying on the green check mark SVG to communicate anything with `<title>` or `<desc>` elements, we may want to mark it as hidden. 

I think some legacy screen readers might try to announce it as an image which might be redundant/confusing unless it's explicitly hidden like so:

```
<svg aria-hidden="true" focusable="false">
  <!-- ... --> 
</svg>
```

**Comment by anastasialanz** [comment]
I think the new `formValue` prop makes sense to implement. 👍🏻

**Comment by dequejosie** [comment]
I like this current approach better (passing in `options` through `Combobox` and `formValue` through `ComboboxOption`). Just a nit on the examples. Do we still need these keys like `key: "123"` in the new examples?

**Comment by Keerthi-Penukonda** [comment]
@scurker can you please provide QA notes to test this ticket?

**Comment by scurker** [comment]
Yes, we should be able to check the below requirements:

> When name is set, a hidden input field will be rendered with the name prop that will have its value set to the formValue of the currently selected combobox option. When formValue is omitted or not set for the selected combobox option, the value of the hidden input will default to the set value or the inner text contents of the selected combobox option.

**Comment by Keerthi-Penukonda** [comment]
Working as expected.


https://github.com/dequelabs/cauldron/assets/40262884/1587fb1f-fd21-47ac-8a49-ec9f180f2ce2
