### ISSUE TITLE
Bug: required TextField components announces required twice

### ISSUE THREAD

**Issue by JoshMK** [dequelabs/cauldron#1293]
### Steps to reproduce

1. Open VoiceOver and tab to a TextField component with required set

### Expected Behavior

Required is only announced once.

### Actual Behavior

Required is announced twice.

### Version

5.12.0

### Anything else we should know?

<img width="1102" alt="Required being announced twice on the TextField component in VoiceOver" src="https://github.com/dequelabs/cauldron/assets/6422248/d1f52b6a-dd52-4e66-af49-92cff2177bb6">

**Comment by scurker** [comment]
I'm hesitant to make this change as the _required_ text exists in the label for support of older screen readers. I haven't seen our own guidelines suggest that this as an issue, so I'm going to defer to our experts here to determine if this is necessary.

**Comment by scurker** [comment]
For now, we'll leave this as is and won't fix. If the need arrises where the design changes or we want to be more comprehensive with form instructions we can update this.
