### ISSUE TITLE
Add Timeline Component

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#1305]
A timeline component is a list of events or items in chronological order. The wrapper of the list is a `ol` element, with each individual item as an `li` element.

## Example

```jsx
<Timeline>
  <TimelineItem>...</TimelineItem>
  <TimelineItem>...</TimelineItem>
  <TimelineItem>...</TimelineItem>
</Timeline>
```

### Design Examples

<details>
  <summary>Light Theme</summary>

![](https://github.com/dequelabs/cauldron/assets/1062039/046eb0b2-997f-45d0-be63-399aeed3ba73)

</details>

<details>
  <summary>Dark Theme</summary>

![](https://github.com/dequelabs/cauldron/assets/1062039/ea615994-ed3e-45be-9dc2-a8001f188d19)

</details>

## Variations

The icon for each `TimeLineItem` defaults to an individual circle. Alternatively, each `TimeLineItem` can customize the icon that is displayed for that item which should override the default icon:

```jsx
<TimelineItem icon={startIcon}>...</TimelineItem>
<TimelineItem>...</TimelineItem>
<TimelineItem>...</TimelineItem>
<TimelineItem icon={endIcon}>...</TimelineItem>
```

**Comment by dequejosie** [comment]
A basic question, what is a `el` element?

**Comment by scurker** [comment]
> A basic question, what is a `el` element?

A typo 🤣

**Comment by thuey** [comment]
In general, this sounds good to me. Just a small question:

The "start" and "end" timeline items also have bold text, in addition to the different icons. Will that styling be applied by default, or is that left up to  the consumer?

**Comment by scurker** [comment]
> The "start" and "end" timeline items also have bold text, in addition to the different icons. Will that styling be applied by default, or is that left up to the consumer?

That's primarily left up to the author. When discussing with @dequelabs/cauldron-design, we wanted to leave that flexible while addressing consistent timeline visualizations and spacing between items.

**Comment by Suvendhu98** [comment]
Hi @scurker ,

any testing is required for the ticket?

**Comment by scurker** [comment]
@Suvendhu98 I don't think so, we should be good to close

**Comment by Suvendhu98** [comment]
Closing the ticket as per above comment
