### ISSUE TITLE
Search Field Enhancements

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#1358]
Outlined are additional enhancements needed for `SearchField`: #1190 

Include a right-oriented "slot" to allow for additional input context to be provided, such as texts, buttons, icons, etc. To achieve this, `SearchField` takes an additional prop named `trailingChildren`, which will be "slotted" into the component. 

Here are a few characteristics of `trailingChildren`:

- it can be anything including strings, elements, or components. 
- it is a child of `TextFieldWrapper` within `SearchField` and is rendered after the native element `input` . 
- visually it is placed after the typing area (including the cancel button) of `TextFieldWrapper`, which is styled as an `input`

Here is a visual example of `SearchField` with the text `1 of 1` and two `IconButton`s as `trailingChildren`:

![search field showing an "X" indicator with a "1 of 1" text and navigational up/down chevron buttons](https://github.com/dequelabs/cauldron/assets/1062039/53140e0d-4f9f-447a-ab06-211105e26e2c)

Here is an usage example:

```js
<SearchField 
  trailingChildren={<MyComponent />} 
  // other props
/>
```

Here is a code snippet of a possible implementation of `trailingChildren` within the `SearchField` component: 

```js
const SearchField = ({
  trailingChildren = "I am a string"
  // other props
}) => {
  // other implementation details
  ...
       <TextFieldWrapper
          className={classNames({
            'TextFieldWrapper--disabled': otherProps.disabled
          })}
       >
          <Icon type="magnifying-glass" className="SearchField__search-icon" />
          <input
            id={inputId}
            value={value}
            onChange={handleChange}
            placeholder={placeholder}
            ref={ref}
            {...otherProps}
            className={classNames(otherProps.className, 'Field__text-input')}
            type="search"
          />
          <span>{trailingChildren}</span>
       </TextFieldWrapper>
}
```

Inside the `SearchField` component, the `trailingChildren` is placed after the native element `input` wrapped by `TextFieldWrapper`. We render it based on the type of `trailingChildren`. In the example above, since we have a string, we render it in a `span`.

**Comment by JoshMK** [comment]
The proposed enhancements look good and make sense. 👍  I just have one question:

In the example implementation, we hardcode a span as the container for `trailingChildren`. Should we give users control to determine the container element? From `<span>{trailingChildren}</span>` to `{trailingChildren}` 👈 (now includes the container itself.)

That would allow slightly more semantic elements for inline text passed as strings, which could be something like `<strong>Search me!</strong>` compared to `<span>Search me!</span>`

(I know screenreader users with vision needs wouldn't be able to pick up on the `<strong>` in the above example, but it could be beneficial for vision-abled screenreader users.)

Thoughts?

**Comment by JoshMK** [comment]
After talking with @dequejosie about this, I think it's fine as is to default it to `<span>` for strings only. Approved.
