### ISSUE TITLE
Radio Select and Checkbox focus indicator does not go around the element evenly.

### ISSUE THREAD

**Issue by okry** [dequelabs/cauldron#137]
I think this might be related to the size of the element being focused since these focus indicators go up to the elements' borders.
Possibly related to #141 

<img width="243" alt="Screen Shot 2020-12-15 at 5 02 05 PM" src="https://user-images.githubusercontent.com/25124347/102278124-43c8a800-3ef7-11eb-846d-5edf814911b1.png">
<img width="243" alt="Screen Shot 2020-12-15 at 5 02 22 PM" src="https://user-images.githubusercontent.com/25124347/102278153-4e833d00-3ef7-11eb-9dfd-151541d314cf.png">

**Comment by dylanb** [comment]
@schne324 is this still a problem? In the billing service UI, this looks fine.

**Comment by okry** [comment]
I'm not seeing the issue anymore. This may have been fixed by a recent ticket. Closing ticket.
