### ISSUE TITLE
[A11y] - Visual heading text is not marked as heading

### ISSUE THREAD

**Issue by VaniChinnam** [dequelabs/cauldron#1388]
### Current Behaviour 
Text appears and functions like a section heading but is not marked up as such. 
Element description 1: Items
Element location: Below the "Default" heading 

Element description 2: Grouped Items
Element location: Below the "With Optional Group Headings".

Also the headings in "With Optional Group Headings" are out of order.
Current:
H3: With Optional Group Headings
H3: OPTIONAL GROUP HEADING
H3: ANOTHER OPTIONAL GROUP HEADING

Expected:
H3: With Optional Group Headings
H4: Grouped Items
H5: OPTIONAL GROUP HEADING
H5: ANOTHER OPTIONAL GROUP HEADING<br/><hr/>
### Expected Behaviour 
`RULE :  Text that acts as a heading visually or structurally MUST be designated as a true heading in the markup. HOW TO FIX:  Fix this issue by using ONE of the following techniques: 1. Use <h1> to <h6> elements to mark text as a heading. Note: Using real HTML headings (<h1>, <h2>, etc.) is preferable when creating new markup. <h1>Types of Web Accessibility Laws</h1> <h2>Civil Rights Laws</h2> <h2>Procurement Laws</h2> <h2>Industry-Specific Laws</h2> 2. When retrofitting legacy markup, using the role="heading" attribute, combined with the aria-level attribute, can be a useful way to add heading semantics to markup without the risk of breaking any styles that might be attached to the legacy markup. The aria-level attribute value is heading level desired. <div class="heading1" role="heading" aria-level="1">Types of Web Accessibility Laws</div> `<br/><hr/>
### Impact 
 <p>

- [ ] Blocker
- [x] Serious
- [ ] Critical
- [ ] Moderate
- [ ] Minor

### Issue Details

<details><summary>View Issue 1513352 </summary> 
 <p>

_**Auditor ID**_ : [1513352](https://axeauditor.dequecloud.com/issue-global-search?searchKeyword=1513352&searchOn=id) 

_**description**_ : undefined 

_**Page Name**_ : Two column panel 

_**source**_ : `<div class="TwoColumnPanel__Header">Grouped Items</div>` 

_**Screenshots**_ : [heading2](https://axeauditor.dequecloud.com/api/v1/file/c4b11800-5d3d-11ee-8c5b-cb4598b88082
Heading1: https://axeauditor.dequecloud.com/api/v1/file/c4b17408-5d3d-11ee-9f69-c387189675d0) 

</p>
</details><details><summary>View Issue 1512246 </summary> 
 <p>

_**Auditor ID**_ : [1512246](https://axeauditor.dequecloud.com/issue-global-search?searchKeyword=1512246&searchOn=id) 

_**description**_ : undefined 

_**Page Name**_ : Accordion 

_**source**_ : `<span class="ExpandCollapse__trigger-title">Accordion #1</span>` 

_**Screenshots**_ : [Visual heading text is not marked as heading](https://axeauditor.dequecloud.com/api/v1/file/690e76fc-5cff-11ee-b3ab-43ba73f532b9) 

</p>
</details>

**Comment by scurker** [comment]
@VaniChinnam cauldron team and I discussed this for a bit. Will comment on the following:

> Element description 1: Items
> Element location: Below the "Default" heading
> Element description 2: Grouped Items
> Element location: Below the "With Optional Group Headings".

The component optionally supports headings that are contextually dependent on the content. In this instance, we don't always consider these items headings and provide a default example to do so. This of course is in context of documentation, so it's not immediately clear to me if this is an issue. Do you have any other recommendations?

> Also the headings in "With Optional Group Headings" are out of order.
> Current:
> H3: With Optional Group Headings
> H3: OPTIONAL GROUP HEADING
> H3: ANOTHER OPTIONAL GROUP HEADING
> Expected:
> H3: With Optional Group Headings
> H4: Grouped Items
> H5: OPTIONAL GROUP HEADING
> H5: ANOTHER OPTIONAL GROUP HEADING

We discussed these and these _are_ the right order of headings and each heading level should not increase, so we believe this to be a false positive.

**Comment by scurker** [comment]
We can add a note to documentation to call out on how the heading order may not match a user's expectation and that a user should appropriately use the right heading levels according to the context in which the component is provided.
