### ISSUE TITLE
Clicking outside of an active modal should close the modal

### ISSUE THREAD

**Issue by okry** [dequelabs/cauldron#139]
When I click outside of a Dialog Modal, the modal should close as it I clicked the `X` button.

**Comment by scurker** [comment]
This could probably be handled with [ClickOutsideListener](https://cauldron.netlify.app/components/ClickOutsideListener)

```jsx

function handleClose() {
  setIsOpen(false)
}

<ClickOutsideListener onClickOutside={handleClose}>
  <Modal show={isOpen}>
   ...
  </Modal>
</ClickOutsideListener>
```

**Comment by schne324** [comment]
I wouldn't be opposed to baking this into `<Modal />` but we definitely can't have it in `<Alert />`

**Comment by awpearlm** [comment]
Closing this. I don't want this to be a thing, at least not right now. Lots of long forms could have their progress blown away by a misclick.
