### ISSUE TITLE
The Modal heading prop should take text as a prop as well as JSX.Elements

### ISSUE THREAD

**Issue by okry** [dequelabs/cauldron#140]
Currently the Modal only takes JSX.Elements as a prop for the heading. The heading prop should take both text and JSX.Elements for ease of use.

**Comment by dylanb** [comment]
Is this still an issue? Why not put a `<span>` around the text?

**Comment by okry** [comment]
Well it just seems a bit much requiring a user to pass in a JSX element. The only reasons I would see that being necessary is if you want icons or mixed styles in your heading. Alternatively, it's for heading elements? If that's the case, we should require the user to pass in a heading element instead of a generic JSX element.

**Comment by schne324** [comment]
👍 sounds like a good enhancement to me!
