### ISSUE TITLE
Cauldron Modal close button not vertically aligned

### ISSUE THREAD

**Issue by okry** [dequelabs/cauldron#146]
<img width="807" alt="Screen Shot 2020-12-21 at 6 26 26 PM" src="https://user-images.githubusercontent.com/25124347/102831532-0a41e200-43ba-11eb-8908-1b4b816bce75.png">

**Comment by schne324** [comment]
@okry are you sure this isn't some style leakage from your app? It looks fine in the demo site (https://cauldron.netlify.app/components/Modal)

**Comment by okry** [comment]
I think this got fixed with the `Icon` and `IconButton` changes a few weeks ago. Closing for now.
