### ISSUE TITLE
Input error elements always take up visual space

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#147]
A recent change in cauldron caused our screenshot testing to break in the axe extension:

<details>
  <summary>Axe Extension Screenshot</summary>

![image](https://user-images.githubusercontent.com/1062039/103227955-4cf14600-48f5-11eb-87a5-e41da53ee80a.png)

</details>

_Guided Tests_ should be aligned with the checkbox, but the `.Error` for the checkbox is causing there to be a misalignment here.

* Should a `<Checkbox />` without a `required` attribute display the error field?
* Should input error elements take up visual space before the error even actually appears?

Removing the `.Error` field or its dimensions would cause a content layout shift if an error actually appears for the given field.

**Comment by okry** [comment]
Fixed
