### ISSUE TITLE
Design Sync: Notice

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#1577]
![screenshot of notice component from figma](https://github.com/user-attachments/assets/8bb61b98-813b-482b-bd70-385870be8c6d)
![screenshot of condensed notice component](https://github.com/user-attachments/assets/6e7b613b-a4fe-4aac-bd71-85fb54889dfd)

To sync with the design, the following changes are needed to notice:

- `variant` property added, defaulting to `default`
- padding changed to `--space-large` for default variant for all borders
- layout is changed for the default variant, a 2-column grid is used with a gap between the icon and title/content of `var(--space-small)`
- a `4px` border radius is added
- `font-size` is removed

A new variant is added, `condensed` with the following changes:

- padding is set to `var(--space-small)` for all borders
- items are displayed within a single column

**Comment by denysfedorov** [comment]
@scurker Hey, Jason!
I have a few questions about this:
1. Should we make this component look like exactly as on Figma or we need to add these properties only?
2. Should we change\modify other parts of `Notice`?

Why I am asking:
For `condensed` in the task description (and figma) we have `Icon` above the `Information` text;
For `condensed` we have approximately `max-width: 50%` for the container (it will look totally different if we only add:
```
padding is set to var(--space-small) for all borders
items are displayed within a single column
```

Also, if we have `max-width` for `variant="condensed"` -> may you send me styles from Figma? (I do not have an access to dev mode)

Thank you in advance!

**Comment by denysfedorov** [comment]
That's how it looks like if we would add changes that are described in the ticket only:


![Image](https://github.com/user-attachments/assets/a2405a0a-e019-4f10-b1c5-4d4d2400ee2b)

**Comment by denysfedorov** [comment]
So, if I will say only from design: seems like we need 1-column layout for both `default` and `condensed` variants, but `condensed` should have thinner width

**Comment by scurker** [comment]
There's no implied width to the notice container. "Condensed" implies the visual layout of how the elements are stacked, and it will be up to the consumer to determine at what width this property gets applied to the component.

> That's how it looks like if we would add changes that are described in the ticket only:
> [...]

That's not quite right. For the default variant, the icon should be in its own column while in the condensed variant all of the elements should be "stacked". You may need to restructure the current component in order to match the designs.
