### ISSUE TITLE
No Visual Difference when Button with variant link is disabled

### ISSUE THREAD

**Issue by JoshMK** [dequelabs/cauldron#1583]
When the Button component with a "link" variant has the `disabled` attribute, it looks visually identical to its active state.

### Steps To Reproduce:

1. Assign the disabled attribute to a Button component with its variant set to link.
2. Observe that there's no visual indication of the state change.

### Current Behavior:

The link variant remains visually identical whether disabled is true or not.

### Expected Behavior:

Buttons with link variants should have a visual disabled state like other variants (primary, secondary etc.)

## Screenshots 

<img width="1092" alt="button with a link variant that does not change visually when deactivated" src="https://github.com/user-attachments/assets/6b9bc03c-a3e7-4dad-aa89-c5faac2bce0c">

**Comment by scurker** [comment]
This isn't something that we really want to support. A better way to implement this coming soon would be tertiary buttons (see #1193).
