### ISSUE TITLE
Bug: `Modal` Component is broken in React 18+

### ISSUE THREAD

**Issue by denysfedorov** [dequelabs/cauldron#1685]
### Steps to reproduce

Assuming you're using React 18+ in your project, when clicking on the modal toggle button to open the modal, the `ClickOutsideListener` calls `handleClickOutside` and then the `close` method in the `Dialog` component. This prevents the modal from opening. Also, you can see this error in the console: 
![image](https://github.com/user-attachments/assets/2d025ba9-6a3b-4be1-8b7c-1f6732293f30)

You can switch the React and React DOM version to 16.14.0 to see it working previously.
https://codesandbox.io/p/sandbox/modal-issue-vxwiht

Similar to: https://github.com/dequelabs/cauldron/issues/1087

### Expected Behavior

When using the `Modal` component in React 18+, the modal should open when triggered and we should not see an error message;

### Actual Behavior

When using the `Modal` component in React 18+, the modal does not open.

### Version

latest

**Comment by ryomtoob** [comment]
@scurker was this addressed by Anastasia's work and can it be closed?

**Comment by scurker** [comment]
Yes, I believe this can be closed. Closing.
