### ISSUE TITLE
Table Design Changes

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#1736]
The Table component has a few visual design updates to align with upcoming features.

## Style Changes

- Add `zebra` striping to rows. 
  - Every table body odd row should a background color of `var(--gray-10)` for light mode and `var(--gray-90)` for dark mode.
- Cell bottom border color changes to `var(--gray-20)`, no changes to dark mode
- Heading color should utilize the same primitive color as the secondary button in their respective mode
- Table cell top/bottom padding changes to 16px, left/right padding 24px for both body and header cells
- Header cells border width is reduced to 1px for both horizontal and vertical layouts

### Sortable Table Headers

- Background/border colors should remain the same as non-sorted cells with the only indication being the sort direction icon (this is removing any existing styles that change the colors)
- The hover state should have a 1px inner focus ring with the same color as the secondary button's focus ring in the respective mode

**Comment by dequejenn** [comment]
Work Effort: Medium
Claude estimation: 3

Visual design updates to the shared Cauldron Table: zebra striping (light/dark tokens), cell border color, header color tied to the secondary-button primitive, padding changes, reduced header border width, and revised sortable-header styling (icon-only indication + 1px inner focus ring on hover) across both modes. Several coordinated style changes on a shared component in both color modes — a 3.
