### ISSUE TITLE
Checkbox's `label` prop forces the use of &nbsp;

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/cauldron#183]
See https://github.com/dequelabs/walnut/pull/1414

@scurker suggested this was due to [`display: flex`](https://github.com/dequelabs/cauldron/blob/9e0b3851941da119b34e61c77cf36116b55aafa5/packages/styles/forms.css#L111).

**Comment by scurker** [comment]
Closing in favor of #182 (duplicate)
