### ISSUE TITLE
Bundle size concerns

### ISSUE THREAD

**Issue by akornmeier** [dequelabs/cauldron#194]
Both `@deque/cauldron-react` and `@deque/cauldron-styles` are noticeably large imports: 

- https://bundlephobia.com/result?p=@deque/cauldron-react@0.0.0
- https://bundlephobia.com/result?p=@deque/cauldron-styles@0.0.0

Are there steps we can take to help minimize the overall import cost?

**Comment by scurker** [comment]
Closing for now, we will look into tackling this in the future with a more refined issue.
