### ISSUE TITLE
Do not rely on/assume font awesome in any components

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#2]
TODO: list all components which currently "assume" font awesome

**Comment by stephenmathieson** [comment]
Yes please! Including _all_ of `font-awesome` for a couple icons seems like overkill.

**Comment by scurker** [comment]
I don't think we rely on font awesome anywhere now (except for docs) (#58)

**Comment by stephenmathieson** [comment]
Can we close this then?

**Comment by scurker** [comment]
Yes
