### ISSUE TITLE
<Pagination /> component

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#205]
![design for pagination](https://user-images.githubusercontent.com/1062039/110979375-2191cb00-832a-11eb-8b49-d95316ffdc88.png)

see uxpin for detailed design

# implementation details:

```ts
interface Props {
  totalItems: number;
  itemsPerPage?: number; // defaults to 10
  currentPage?: number; // defaults to 1
  statusLabel?: React.ReactElement; // defaults to "Showing x-y of {total}"
  firstPageLabel?: React.ReactElement; // defaults to "First page"
  previousPageLabel?: React.ReactElement; // defaults to "Previous page"
  nextPageLabel?: React.ReactElement; // defaults to "Next page"
  lastPageLabel?: React.ReactElement; // defaults to "Last page"
  onNextPageClick?: () => void;
  onPreviousPageClick?: () => void;
  onFirstPageClick?: () => void;
  onLastPageClick?: () => void;
}

<Pagination
  totalItems={15}
  itemsPerPage={5} // optional
  currentPage={1} // optional
  statusLabel={i18n`Showing 1-5 of 15`}
/>
```

- Use the `<IconButton />` with *label* (tooltip with *Label props)
- Component should manage (derive) disabled state of buttons. For example, on the first page, 'first page' and 'previous page' should be disabled. For each disabled control use `<TooltipTabstop />` so it can remain focusable/tooltip-able (obviously don't invoke the associated click listeners on disabled controls).
- wrap the `statusLabel` in a `role="log" aria-atomic="true"` (and test that this works as you navigate through the pages

**Comment by schne324** [comment]
```ts
interface Props {
  totalItems: number;
  itemsPerPage?: number; // defaults to 10
  currentPage?: number; // defaults to 1
  statusLabel?: React.ReactElement; // defaults to "Showing x-y of {total}"
  firstPageLabel?: React.ReactElement; // defaults to "First page"
  previousPageLabel?: React.ReactElement; // defaults to "Previous page"
  nextPageLabel?: React.ReactElement; // defaults to "Next page"
  lastPageLabel?: React.ReactElement; // defaults to "Last page"
  onNextPageClick?: () => void;
  onPreviousPageClick?: () => void;
  onFirstPageClick?: () => void;
  onLastPageClick?: () => void;
}

<Pagination
  totalItems={15}
  itemsPerPage={5} // optional
  currentPage={1} // optional
  statusLabel={i18n`Showing 1-5 of 15`}
/>
```

- Use the `<IconButton />` with *label* (tooltip with *Label props)
- Component should manage (derive) disabled state of buttons. For example, on the first page, 'first page' and 'previous page' should be disabled. For each disabled control use `<TooltipTabstop />` so it can remain focusable/tooltip-able (obviously don't invoke the associated click listeners on disabled controls).
- wrap the `statusLabel` in a `role="log" aria-atomic="true"` (and test that this works as you navigate through the pages

**Comment by okry** [comment]
Finished
