### ISSUE TITLE
Tooltips are using keyup listeners

### ISSUE THREAD

**Issue by okry** [dequelabs/cauldron#221]
The tooltips are using `keyup` listeners which cause unexpected results when interacting with other elements. We should always be defaulting to use `keydown` listeners on keyboard events unless there is an explicit reason to do otherwise.

**Comment by okry** [comment]
Need to test this, but I think with the current implementation, the `escape` key event is getting propogated and is doing thing like closing modals which is unwanted.

**Comment by scurker** [comment]
This is intended and won't change. We will address the modal issue with #1597
