### ISSUE TITLE
ExpandCollapsePanel produces invalid HTML

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/cauldron#224]
The `<ExpandCollapsePanel>` component creates the following DOM:

```html
<button class="ExpandCollapse__trigger" type="button" aria-expanded="false">
  More bacon info
  <div aria-hidden="true" class="Icon Icon--chevron-right Icon__right">
    <svg><!-- ... --></svg>
  </div>
</button>
```

This is not valid HTML, as a `<button>` may not contain a `<div>`.

To test, I copied the outer HTML of the element matching `#main-content > div` from https://cauldron.netlify.app/components/ExpandCollapsePanel and pasted the following into the W3 HTML validator:

```html
<!doctype html>
<html lang="en">
<title>Test</title>

<!-- PASTE OUTER HTML HERE -->

</html>
```

**Comment by anastasialanz** [comment]
I created a similar issue here where you can't use the `Icon` component inside of a `p` tag. https://github.com/dequelabs/cauldron/issues/668

**Comment by somaalapati** [comment]
@stephenmathieson Where should I verify this? Not super familiar with Cauldron testing.

**Comment by anastasialanz** [comment]
> @stephenmathieson Where should I verify this? Not super familiar with Cauldron testing.

You can check https://cauldron.dequelabs.com/. I see that my change is live there.

**Comment by somaalapati** [comment]
Now the span replaced the div, so closing this ticket. Thanks @anastasialanz for providing the details.

![image](https://user-images.githubusercontent.com/40261789/200293237-3f2a6d8b-700c-4a85-993c-ca89f06c3c59.png)
