### ISSUE TITLE
Add `share` icon

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#246]
See UX pin for Icon (ask @scurker or @awpearlm if you don't have access)

**Comment by Keerthi-Penukonda** [comment]
We don't have a share Icon at the "share issue" button.

 **Screenshot:**
![image](https://user-images.githubusercontent.com/40262884/118766859-9fc69c80-b89a-11eb-96da-be38e7e7083b.png)


**UX Pin:**
![image](https://user-images.githubusercontent.com/40262884/118766801-8e7d9000-b89a-11eb-8509-ea8b9a204b3c.png)

**Tested Environment:**
**Axe DevTools Pro:** 4.9.3.13900 Dev build
**Chrome Browser:** Version 90.0.4430.93 (Official Build) (64-bit)
**Server:** https://axe.dequelabs.com/
**OS:** MS Windows 10

**Comment by erik-deque** [comment]
It has been added per #249
