### ISSUE TITLE
Buttons hover ring is off on the right side 

### ISSUE THREAD

**Issue by awpearlm** [dequelabs/cauldron#253]
The hover ring is touching the right side of the button:
![image](https://user-images.githubusercontent.com/5720243/118836167-a1d82d80-b891-11eb-9135-164b6f821748.png)

**Comment by schne324** [comment]
@awpearlm it appears that either this issue has been fixed or, more likely, there is an issue with styles in whatever app that screenshot was taken from.

<img width="503" alt="Screen Shot 2021-07-28 at 7 56 31 PM" src="https://user-images.githubusercontent.com/3180185/127424474-35e59416-381a-49da-b387-7265ece9d2b8.png">

https://cauldron.netlify.app/components/Button
