### ISSUE TITLE
Modals and zoom

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#28]
Modals don't play nice with small viewport and zoom. Below is a screenshot of the extension zoomed @ 200% with a modal:

![axe extension with modal](https://user-images.githubusercontent.com/1062039/81451011-2e152800-9149-11ea-8baf-553f8fd782f9.png)

**Comment by schne324** [comment]
Agreed upon solution (Jason and Harris): Make the scrim the scrollable / fixed region

**Comment by scurker** [comment]
This should be fixed by #88
