### ISSUE TITLE
Bump button thin variants and icon buttons to 24px

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#306]
WCAG 2.2 AA guidelines will now require target sizing to be a minimum of 24px:
https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/

> Target size (minimum): Renamed (from Pointer target Spacing), reduced the core size requirement to 24px, and simplified the criterion text.

## Impacts

- Button (thin variant)
- IconButton (both height/width should match minimum target size)

**Comment by okry** [comment]
Pending official release of WCAG 2.2 guidelines.

**Comment by scurker** [comment]
We need to match whatever UXpin is here, it looks like uxpin has the target size > 24px

**Comment by scurker** [comment]
This is done.
