### ISSUE TITLE
Add support for dark/light theme buttons and links

### ISSUE THREAD

**Issue by vicdq** [dequelabs/cauldron#322]
https://preview.uxpin.com/524c996762ba2e2235b6f9cd98295494870749fe#/pages/137867771/simulate/no-panels

https://preview.uxpin.com/4052c8b6f05ce03e28813f28deb3a682950c2ac6#/pages/140808121/specification/no-panels

https://preview.uxpin.com/68df515d0023cc4b79f25d43f7663e24e363b1b9#/pages/141465361/simulate/no-panels

**Comment by somaalapati** [comment]
Caldron stuff. Not possible to verify it on Axe Pro.
