### ISSUE TITLE
Support dark/light theme for modals and tabs

### ISSUE THREAD

**Issue by vicdq** [dequelabs/cauldron#325]
Support dark/light theme for modals and tabs

https://preview.uxpin.com/5a35f510bfb55e3e77f9dbd54a49203736113855#/pages/139030159

https://preview.uxpin.com/5a35f510bfb55e3e77f9dbd54a49203736113855#/pages/139000277

**Comment by somaalapati** [comment]
Caldron stuff. Not possible to verify it on Axe Pro.
