### ISSUE TITLE
Light theme's sidebar hover/focus indication is wrong

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#331]
Actual:
<img width="276" alt="Screen Shot 2021-09-17 at 11 00 13 AM" src="https://user-images.githubusercontent.com/3180185/133833343-40e1464f-a32f-4686-ad85-a91d70ad9cde.png">

Expected:
<img width="282" alt="Screen Shot 2021-09-17 at 10 58 19 AM" src="https://user-images.githubusercontent.com/3180185/133833299-fd4183d3-0409-4fcc-8516-e33af694c8d5.png">

## Dev Notes:

use the color `var(--accent-primary)` https://preview.uxpin.com/5ca5c040146a4ebb4536c10998dd84d1199e5d79#/pages/133873611/specification/sitemap

**Comment by okry** [comment]
This will also need to be updated in the TopBar.

**Comment by scurker** [comment]
Related to #587, I don't think we need both issues.
