### ISSUE TITLE
Dark theme's dialogs' headers have color contrast issue

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#333]
<img width="454" alt="Screen Shot 2021-09-17 at 11 03 14 AM" src="https://user-images.githubusercontent.com/3180185/133833802-dc35fc34-dc6f-4db7-b2cd-449ed8851bbf.png">

See uxpin for details on what it should be https://preview.uxpin.com/4052c8b6f05ce03e28813f28deb3a682950c2ac6#/pages/140808220/simulate/no-panels

**Comment by scurker** [comment]
I think this should be addressed in this PR https://github.com/dequelabs/cauldron/pull/329

**Comment by schne324** [comment]
duplicate of #325
