### ISSUE TITLE
Dark theme loader is off

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#337]
<img width="112" alt="Screen Shot 2021-09-17 at 11 12 29 AM" src="https://user-images.githubusercontent.com/3180185/133834806-a3516d17-89b2-43ef-b501-898bbee95f51.png">

**Comment by thuey** [comment]
As part of this, the center should be transparent

**Comment by awpearlm** [comment]
Note: Doing #460 will remedy this issue.
