### ISSUE TITLE
Sync Alert modals with UXpin

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#358]
## Light Mode

[uxpin](https://preview.uxpin.com/520e80315786a67ba43a3ca50598e6d69782627c#/pages/161666306/simulate/no-panels?mode=i)

![light mode alert modal info variant](https://github.com/dequelabs/cauldron/assets/1062039/fd5cb421-e47e-4c7f-be48-92b2a9afb8e2)

![light mode alert modal warning variant](https://github.com/dequelabs/cauldron/assets/1062039/725c3ffd-0ba7-4983-966b-cb1f19c8d11c)

## Dark Mode

![dark mode alert modal info variant](https://github.com/dequelabs/cauldron/assets/1062039/e001f5b3-cd12-45f9-aca1-e8df41c3ad64)

![dark mode alert modal warning variant](https://github.com/dequelabs/cauldron/assets/1062039/e80d4bd9-4da6-4f0b-8011-56038f7b4c96)

**Comment by scurker** [comment]
@bobbyomari Is this still out of line with cauldron?

**Comment by bobbyomari** [comment]
There are 3 types of modals and should be styled as such: https://preview.uxpin.com/4052c8b6f05ce03e28813f28deb3a682950c2ac6#/pages/140808127

In this case, the OP example was for a destructive action so it should use the Error Modal example instead of a standard modal.

**Comment by scurker** [comment]
These are specifically the alert modals (which are a variation of dialog): https://cauldron.dequelabs.com/components/Alert

**Comment by scurker** [comment]
fixed by #1275
