### ISSUE TITLE
Select, input, and textarea's css should only affect Cauldron's components

### ISSUE THREAD

**Issue by dequejosie** [dequelabs/cauldron#367]
For the discussion on this issue: see https://github.com/dequelabs/cauldron/pull/366

**Comment by okry** [comment]
Related to #635

**Comment by scurker** [comment]
@dequelabs/cauldron-design and I discussed during a recent one-on-one. We decided this is not going to be a change we pursue. Cauldron is intended to be a design system you build on top of and not adjacent to other systems. We realize there may be some friction if you need to use native html components for other things, but some friction is desired to lead to better consistency with natural inputs.
