### ISSUE TITLE
Implement nav bar component

### ISSUE THREAD

**Issue by dylanb** [dequelabs/cauldron#382]
Steal as much of the implementation from Walnut as possible

Light: https://preview.uxpin.com/68df515d0023cc4b79f25d43f7663e24e363b1b9#/pages/141465415

**Comment by somaalapati** [comment]
@dylanb Is this testable by QA?

**Comment by Keerthi-Penukonda** [comment]
Working as expected.

**Screenshots:**
![image](https://user-images.githubusercontent.com/40262884/142982873-f9ba2b0f-0ac3-49a6-8a3a-3f05f2fed7dc.png)
![image](https://user-images.githubusercontent.com/40262884/142982950-b4c88a3c-1dde-4450-b481-c0e6b8793e69.png)
