### ISSUE TITLE
Cannot use React Hooks for components until demos are updated

### ISSUE THREAD

**Issue by okry** [dequelabs/cauldron#40]
Since the Cauldron React Demos are using class-based React and some of the react components use functional React, there is a conflict between the react versions that prevent us from using React hooks in the components of `cauldron-react`.

In order to use these hooks, we will need to update the Demo files to be written in functional React to synchronize the versions.

**Comment by stephenmathieson** [comment]
I don't think this is correct. You should be able to use hooks in your project regardless of what the demo components do.

**Comment by okry** [comment]
You're right, proof since there's a bunch of PRs already using hooks in the components without breaking the rules of hooks. Closing issue.
