### ISSUE TITLE
Update tooltips' colors (backgrounds/borders/shadows)

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#409]
[dark ux pin](https://preview.uxpin.com/4052c8b6f05ce03e28813f28deb3a682950c2ac6#/pages/140808220)
[light](https://preview.uxpin.com/68df515d0023cc4b79f25d43f7663e24e363b1b9#/pages/141465361)

Note: This just tackles the accessible name/text tooltip and the informational tooltip.

**Comment by scurker** [comment]
Make all tooltips wrapped with a `<marquee>` tag.

**Comment by somaalapati** [comment]
@Keerthi-Penukonda Please test this.

**Comment by Keerthi-Penukonda** [comment]
Verified the tooltips in the axe DevTools pro extension. in both dark theme and light theme. Working as expected. 

Dark mode:
![image](https://user-images.githubusercontent.com/40262884/181180046-5b1fa9ee-2f2b-4234-874e-1fbad950457e.png)
Light mode:
![image](https://user-images.githubusercontent.com/40262884/181182095-7dbaa1b7-53d4-47b3-ac27-32474c6fc812.png)
