### ISSUE TITLE
Fix topbar dropdown

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#43]
![image](https://user-images.githubusercontent.com/1062039/87182470-ce9eda00-c2a9-11ea-97ec-d12112bd1179.png)

**Comment by okry** [comment]
https://preview.uxpin.com/68df515d0023cc4b79f25d43f7663e24e363b1b9#/pages/141465425/simulate/no-panels
We want the dropdown to be flush with the bottom of the TopBar.

**Comment by scurker** [comment]
duplicate of #1073
