### ISSUE TITLE
Add support for `<ExpandCollapsePanel>` to have a heading as the trigger.

### ISSUE THREAD

**Issue by ryomtoob** [dequelabs/cauldron#437]
Currently there's not a good way to allow the trigger of `<ExpandCollapsePanel>` to have a heading in it. Putting the heading inside the `<PanelTrigger>` results in a heading inside a button which is an accessibility issue. Wrapping the `<PanelTrigger>` in a heading causes it to disappear.

**Comment by tbusillo** [comment]
@okry @ryomtoob this [should now be supported](https://github.com/dequelabs/cauldron/pull/669/files#diff-47ff2880b1c9c2c1f0fb2f24ec63fb5efe1c3ed3c4aeaf688cde07806a35f825).

**Comment by ryomtoob** [comment]
@okry the use case I had for this was the HTML reports in [axe-devtools-reporter](https://github.com/dequelabs/axe-devtools-reporter). IIRC I used an offscreen heading instead. @tbusillo great! I think this issue can be closed then, and the proper course of action would be to replace the `<ExpandCollapsePanel>` in the reporter with the `<Accordion>` component.

**Comment by ryomtoob** [comment]
Awesome, thanks Tom!
