### ISSUE TITLE
Support sortability of `<Table />`

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#489]
[see uxpin's sortable table examples](https://preview.uxpin.com/4052c8b6f05ce03e28813f28deb3a682950c2ac6#/pages/140808126/simulate/sitemap)

As far as accessibility goes, feel free to ping @schne324 or check out [dqu's example](https://dequeuniversity.com/library/aria/table-sortable)

The callers of the component will handle the actual sorting of data and it is up to them to inform the `<Table />` component of what the sort state is.

**Comment by dequejosie** [comment]
This is also needed by https://github.com/dequelabs/walnut/issues/2665

**Comment by somaalapati** [comment]
Verified this ticket by testing the sorting feature on the users table in ticket https://github.com/dequelabs/walnut/issues/2663. Everything looks good, so closing the ticket.
