### ISSUE TITLE
Table columns width % need to be able to be set on a column by column basis

### ISSUE THREAD

**Issue by awpearlm** [dequelabs/cauldron#516]
The table component currently has all the columns evenly split across across the width. So if there are 4 columns, each one takes up 25% of the space. However there aren't any tables in any of the designs where the columns are all perfectly even. Columns width get set in the design based on the needs of the content. So the columns need to have their % set at will.

Example of a table with uneven column widths:
![image](https://user-images.githubusercontent.com/5720243/150000515-4c2a9359-ba9a-4dc1-a8d8-5028992399de.png)

**Comment by scurker** [comment]
We should use `table-layout: auto` to let the browser choose an appropriate layout based on the data provided for the table.
