### ISSUE TITLE
Missing bottom margin for select lists, text inputs and text areas

### ISSUE THREAD

**Issue by awpearlm** [dequelabs/cauldron#538]
There should be ~24px~ 16px from the bottom of the input to the element below it.

Example: 
![image](https://user-images.githubusercontent.com/5720243/152193400-753f2c51-2b4c-4c01-9605-421fc06f4c01.png)

When error is present (additionally push the below elements down the distance of the error footprint ~15px <-- confirm this):
![image](https://user-images.githubusercontent.com/5720243/152194236-bfc346c4-06dd-4100-8ea7-0aa2fc5604a3.png)

**Comment by dequejosie** [comment]
If I recall correctly, we should fix Checkbox as well.

**Comment by awpearlm** [comment]
Small note: I spoke with Bobby and Josie. The space value should be 16px, not 24px. So Josie has it changed in the PR to be 16px and that is correct.

**Comment by somaalapati** [comment]
@dequejosie I struggling to understand this. Which component of axe DevTools Pro I can test this change? Or this issue only with Caldron components?

**Comment by dequejosie** [comment]
@somaalapati this ticket itself is for Cauldron, but once we update Cauldron version in Webapp and axe extension, we will see all the areas with TextFields and Select change. Actually I will spend some time tomorrow to update and take a look at the changes.

**Comment by dequejosie** [comment]
@somaalapati For the impact of this ticket on Walnut, please check dev once this pr is merged: https://github.com/dequelabs/walnut/pull/3036, which is a part of https://github.com/dequelabs/walnut/issues/2961.

**Comment by dequejosie** [comment]
@somaalapati you should be able to see the enlarged margins after this pr https://github.com/dequelabs/axe-extension/pull/2348 gets merged.

**Comment by dequejosie** [comment]
This ticket should be ready for test both in Walnut and extension repo. @somaalapati @Keerthi-Penukonda @karthikeyan2716

**Comment by karthikeyan2716** [comment]
**Retesting details:**
- This is working as expected 

**Screenshot:**

![30-03-2022-04-58-02](https://user-images.githubusercontent.com/79319620/160824333-5f0d4f3f-0c5e-4bb2-9993-1c6ede427f77.png)

![30-03-2022-04-57-19](https://user-images.githubusercontent.com/79319620/160824222-f30bf3a9-dbac-4cae-8488-2274c7685570.png)

![30-03-2022-04-57-04](https://user-images.githubusercontent.com/79319620/160824187-a4406872-74db-4088-9517-9b11316ff0a8.png)




![30-03-2022-04-57-25](https://user-images.githubusercontent.com/79319620/160824240-6ee3ed80-d41e-4d34-b0de-777a18f1d6cf.png)



**Walnut Version:** 4.42.2
