### ISSUE TITLE
The position of Tooltip does not match the position of Icon Button after sorting

### ISSUE THREAD

**Issue by dequejosie** [dequelabs/cauldron#539]
Once the default order of the items changes, the position of Tooltip stops matching the position of Icon Button. In the screenshot below, I was hovering the icon on the third row, which used to be the first row before sorting, and the tooltip of the icon on the first row pops up. It is probably related to how Popper works. Additional information is, after resizing the viewport, this bizarre behavior disappears.

To reproduce this issue, please go to User Management on WebApp dev with multiple items. Sort, and then the issue will occur.

Given that sortable Table plus Icon Buttons appear in multiple places in our WebApp, we probably need to fix this soon.

<img width="1247" alt="Screen Shot 2022-02-03 at 5 44 02 PM" src="https://user-images.githubusercontent.com/83524297/152445624-c94c372d-ae0d-4bd7-958f-7b95f3486612.png">

**Comment by somaalapati** [comment]
@karthikeyan2716 Please test this ticket.

**Comment by karthikeyan2716** [comment]
**Retesting details:**

- It is working as expected
- The position of Tooltip matches the position of Icon Button after sorting

**Recording:**

https://user-images.githubusercontent.com/79319620/155658035-a7476093-2643-480d-91f9-4044192d1d01.mp4




**Tested Environment:**
**Walnut Version:** 4.41.1 build
**Chrome Browser:** Version 98.0.4758.102 (Official Build) (64-bit)
**Server:** https://axe.dequelabs.com/
**OS:** MS Windows 10
