### ISSUE TITLE
Tooltip show prop does not work as expected

### ISSUE THREAD

**Issue by thuey** [dequelabs/cauldron#546]
There are a couple of issues with the Tooltip show prop:

1. According to the documentation, `show` is supposed to manually control the visibility of the tooltip. However, it doesn't work because `show` is only used to initialize the state of whether or not the tooltip appears.
2. `show` is defaulted to `false` (see: https://github.com/dequelabs/cauldron/blob/16adb90060f3962eb6a7df4bce421c1dd8f056b3/packages/react/src/components/Tooltip/index.tsx#L48), so if we started treating `show` as a manual override, the current automatic hide/show code would stop working (because it would always be overridden by `show`)

Fixing these issues will be a breaking change

**Comment by scurker** [comment]
After further evaluation, this should _not_ be a breaking change. We have the prop documented as following: 

> Manually control the show state of the tooltip.

With the original intention being that this was to change the component from uncontrolled to controlled when the `show` prop was set. I could not find any internal usages of the component in this way so we can move forward.

If the "initial show" behavior is desired, a new prop `defaultShow` will be added to accommodate this.
