### ISSUE TITLE
Sortable Columns of Table are missing hover state

### ISSUE THREAD

**Issue by dequejosie** [dequelabs/cauldron#551]
Expected:

<img width="355" alt="Screen Shot 2022-02-28 at 3 52 48 PM" src="https://user-images.githubusercontent.com/83524297/156056857-1ccd8b32-65b6-48d8-8e2c-7f21ed6d4c70.png">

**Comment by dequejosie** [comment]
Please test this with walnut User Management's table. Hover the sortable columns (with triangle icons) and see if the color changes.

**Comment by somaalapati** [comment]
working as expected

https://user-images.githubusercontent.com/40261789/157207572-f1dbb42c-3f9f-4cbd-8154-7372a8ab7df2.mp4


"version":"4.42.1"
