### ISSUE TITLE
Support for React 17

### ISSUE THREAD

**Issue by washtenawIdtreble** [dequelabs/cauldron#555]
## Expected Behavior
`npm install --save @deque/cauldron-react @deque/cauldron-styles` works with new React apps created with `create-react-app`

## Actual Behavior
When I run `npm install --save @deque/cauldron-react @deque/cauldron-styles`, I get the following error:
```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: washtenaw-id-webapp@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.6.0" from @deque/cauldron-react@4.1.0
npm ERR! node_modules/@deque/cauldron-react
npm ERR!   @deque/cauldron-react@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See ~/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2022-03-03T14_52_04_004Z-debug-0.log
```
React 17 has been out for [almost 18 months](https://reactjs.org/blog/2020/10/20/react-v17.html), and is a stepping-stone release with no new features. I guess I could try installing Cauldron with --force and it should work, but I don't want to hang my whole app on that working in the long run.

## Steps to Reproduce the Problem

  1. Create a new React app with `create-react-app` and Typescript: `npx create-react-app my-app --template typescript && cd my-app`
  1. Install Cauldron: `npm install --save @deque/cauldron-react @deque/cauldron-styles`

## Specifications

  - Versions:
    - NodeJS: 16.13.0
    - npm: 8.5.1
  - Platform:
    - Pop_OS 21.10

**Comment by anastasialanz** [comment]
I'm seeing this same issue when updating to React 17 in our Next app.

**Comment by stephenmathieson** [comment]
This should now be resolved. Feel free to reopen if you run into issues!
