### ISSUE TITLE
Add utilities to handle text wrapping (for long strings like email addresses, urls, etc.)

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#557]
This should be supported both by a css utility class and a utility component.

Methods of wrapping should include:
- Truncation/ellipsize (an alternative to the full text must be provided in order to pass wcag)
- Word breaks (break on spaces, break on all)
- Hyphenated

For the utility component, it would utilize the utility classes provided (defaulting to break-word):

```jsx
<TextWrap strategy="break-word">
  ...
</TextWrap>
```

This affects most components, for example, the alert 👇 
<img width="731" alt="Cauldron alert with harris@ repeated multiple times to overflow outside of the boundaries of the alert" src="https://user-images.githubusercontent.com/3180185/157098791-a1345f7e-c346-4afc-af2b-95056e36d8cb.png">

**Comment by scurker** [comment]
I believe the [`<TextEllipsis>`](https://cauldron.dequelabs.com/components/TextEllipsis) component should cover the use cases we have here.
