### ISSUE TITLE
Docs site issue: Alert button text cutoff at 320px viewport width

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#572]
![image](https://user-images.githubusercontent.com/3180185/159586266-dcac5a43-d2d0-4b70-a1c4-6ecb1924ac2b.png)

<dl><dt>Description</dt><dd>Content or functionality is lost due to overlapping content when page width is adjusted to 320px.
Button under 'Warning Alert' dialog - 
1. Let's get Dangerous 
</dd><dt>Impact</dt><dd>Serious</dd><dt>Recommendation</dt><dd>RULE : 
Content MUST be presented without loss of information or functionality when the viewport is set to 320 CSS pixels wide.

HOW TO FIX: 
Fix this issue by ensuring content does not overlap other content when the screen width is set to 320px by using techniques such as CSS media queries, grids, or flexbox to reflow content down to 320px width.

REFERENCE: 
Deque University:https://dequeuniversity.com/class/responsive-zoom2/zoom/linear-text-reflow
https://dequeuniversity.com/class/responsive-zoom2/responsive/
WCAG Understanding document:
https://www.w3.org/WAI/WCAG21/Understanding/reflow

BACKGROUND: 
People with low vision often read content on a desktop computer by scaling content using the browser zoom - up to 400%. When zooming causes content to overlap other content, users with low vision may not be able to see or use that content. When content is created so that it reflows without losing information or functionality at screen widths down to 320px, users can view a web page in a 1280px width browser screen and zoom the content to 400% (320px) without having to scroll side to side to read and without losing access to content.</dd><dt>Source code</dt><dd><pre><code><button type="button" class="Button--error">Let's get dangerous</button>
</code></pre></dd><dt>Checkpoint</dt><dd>Reflow (1.4.10.a)</dd><dt>URL</dt><dd>https://cauldron.dequelabs.com/components/Alert</dd></dl>

**Comment by okry** [comment]
Fixed
