### ISSUE TITLE
Tooltip alignment issues at 320px (viewport width)

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#577]
![image](https://user-images.githubusercontent.com/3180185/159585594-7708b053-a1de-470d-8f63-151da6dc472e.png)

---

<dl><dt>Description</dt><dd>Page is not responsive at 320px
Tool tip page is not responsive at 320px setting. 
To observe this issue - perform forward navigation and then back navigation using Tab and Shift+Tab keyboard keys. </dd><dt>Impact</dt><dd>Minor</dd><dt>Recommendation</dt><dd>RULE : 
Content MUST be presented without loss of information or functionality when the viewport is set to 320 CSS pixels wide.

HOW TO FIX: 
Fix this issue by ensuring content does not overlap other content when the screen width is set to 320px by using techniques such as CSS media queries, grids, or flexbox to reflow content down to 320px width.

REFERENCE: 
Deque University:https://dequeuniversity.com/class/responsive-zoom2/zoom/linear-text-reflow
https://dequeuniversity.com/class/responsive-zoom2/responsive/
WCAG Understanding document:
https://www.w3.org/WAI/WCAG21/Understanding/reflow

BACKGROUND: 
People with low vision often read content on a desktop computer by scaling content using the browser zoom - up to 400%. When zooming causes content to overlap other content, users with low vision may not be able to see or use that content. When content is created so that it reflows without losing information or functionality at screen widths down to 320px, users can view a web page in a 1280px width browser screen and zoom the content to 400% (320px) without having to scroll side to side to read and without losing access to content.</dd></dd><dt>Checkpoint</dt><dd>Reflow (1.4.10.a)</dd><dt>URL</dt><dd>https://cauldron.dequelabs.com/components/Tooltip</dd></dl>

**Comment by okry** [comment]
@schne324 Is this still reproducible?
