### ISSUE TITLE
Docs site issue: Buttons are overlapping at 320px (on alert demo page)

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#580]
![8ded0754-736d-11ec-b450-ef9486c20ec9](https://user-images.githubusercontent.com/3180185/159584743-17956ac8-1abc-42f7-a02e-e5020699a3dd.png)

---
<dl><dt>Description</dt><dd>Elements are overlapping to each other when page at 320px

1. Default Alert 
2. Warning Alert</dd><dt>Impact</dt><dd>Moderate</dd><dt>Recommendation</dt><dd>RULE : 
Content MUST be presented without loss of information or functionality when the viewport is set to 320 CSS pixels wide.

HOW TO FIX: 
Fix this issue by ensuring content does not overlap other content when the screen width is set to 320px by using techniques such as CSS media queries, grids, or flexbox to reflow content down to 320px width.

REFERENCE: 
Deque University:https://dequeuniversity.com/class/responsive-zoom2/zoom/linear-text-reflow
https://dequeuniversity.com/class/responsive-zoom2/responsive/
WCAG Understanding document:
https://www.w3.org/WAI/WCAG21/Understanding/reflow

BACKGROUND: 
People with low vision often read content on a desktop computer by scaling content using the browser zoom - up to 400%. When zooming causes content to overlap other content, users with low vision may not be able to see or use that content. When content is created so that it reflows without losing information or functionality at screen widths down to 320px, users can view a web page in a 1280px width browser screen and zoom the content to 400% (320px) without having to scroll side to side to read and without losing access to content.</dd><dt>Source code</dt><dd>
```html
<button type="button" class="Button--primary">Default Alert</button>
```

</dd><dt>Checkpoint</dt><dd>Reflow (1.4.10.a)</dd><dt>URL</dt><dd>https://cauldron.dequelabs.com/components/Alert</dd></dl>

**Comment by ryomtoob** [comment]
This was resolved in #770
