### ISSUE TITLE
Update Two Column Panel to add skip link

### ISSUE THREAD

**Issue by dylanb** [dequelabs/cauldron#598]
Make an option that allows a skip link to be displayed above the left navigation that allows the user to skip to the collapse component

add an optional `skipLink` property: `skipLink={<SkipLink to="#session" skipText="Session" />}`

When the skip link property is present, it should only be shown:

* When the panel is expanded
* In the narrow view it should never be shown (if it's only shown when expanded and is outside of the focus trap, we may not need any special cases for the narrowest view)

**Comment by somaalapati** [comment]
@AdnoC I don't have an idea where exactly I need to verify this change on the Walnut application. Is this a Cauldron ticket? 
Can you please provide some details on how to test this ticket?

**Comment by AdnoC** [comment]
I tested this by modifying https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/TwoColumnPanel/index.js to use a `SkipLink` in one of the examples and then doing [`yarn dev`](https://github.com/dequelabs/cauldron#dev) to start a local docs server. I went to the page for the two column panel and verified there.

**Comment by somaalapati** [comment]
@AdnoC  Thanks for the testing feedback. 
Closing this ticket based on Adam's feedback as QA can't verify this ticket.
