### ISSUE TITLE
Backport Radio/Checkbox Fix

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#606]
Once the fix for #585/#590 is released to `v4.0.0`, we should cherry-pick the change into prior versions to ensure the fix also gets included for older versions of cauldron to ensure our checkboxes/radio are accessible there.

- [ ] `v1.0.0`
- [ ] `v2.0.0`
- [ ] `v3.0.0`

**Comment by stephenmathieson** [comment]
Do we support versions older than the current major? If so, why?

**Comment by scurker** [comment]
I don't know if every team here has updated to `v4` since each major release contains breaking changes. `v1` is only about ~8 months old so it's very likely that someone could still be on that version. Since this issue is a critical accessibility issue and would prevent access to someone using NVDA both @schne324 and I discussed back-porting all the way back.

**Comment by schne324** [comment]
If you're encountering this bug and need this fix, please let us know and we will do the work to backfill this a11y fix.

**Comment by scurker** [comment]
I'm guessing this is not a priority given we haven't received any reports on this, so closing as won't fix.
