### ISSUE TITLE
Hotdog mode

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/cauldron#616]
Inspired by StackOverflow.

We support light/dark mode. Why not hotdog mode?

<img width="1290" alt="StackOverflow in hotdog mode" src="https://user-images.githubusercontent.com/571265/161284908-727815fa-a391-436d-82de-1e12acf97e68.png">

**Comment by awpearlm** [comment]
We need to write some hotdog firmware so an actual hotdog can be used as a peripheral. Does anyone know assembly?

**Comment by stephenmathieson** [comment]
My assembler experience is 10+ years old, haven't touched it since [Turbo Assembler](https://en.wikipedia.org/wiki/Turbo_Assembler). That said, I'm very confident in my ability to write firmware for a hotdog.

**Comment by scurker** [comment]
Since it sounds like you have the most hotdog experience, I'm going to assign it to you.

**Comment by scurker** [comment]
Unfortunately, I do not think we are going to have time to allocate to hot dog mode. Should hot dog mode become important for business purposes, we will reconsider implementing this.

**Comment by stephenmathieson** [comment]
😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭😢🌭
