### ISSUE TITLE
Text wrapping on `<Button thin>`

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#620]
![thin button with "change axe devtools pro plan" with little to no vertical spacing](https://user-images.githubusercontent.com/1062039/161836517-99845ee7-5930-4716-b4fb-21e70232b4ea.png)

It looks like there's a few more tweaks we need to make [here](https://github.com/dequelabs/cauldron/blob/61754b20d7a4ca320d0600047c0b959dd1427a4d/packages/styles/button.css#L185). We should remove `line-height` and instead rely on top/bottom padding to properly set the text alignment within the button so that when the button wraps it has the proper spacing.

**Comment by Bracciata** [comment]
Tackled this one in PR #1046
