### ISSUE TITLE
tabIndex is not in the Props interface for the <Code> component, so the overflow scrollbar cannot be focused in Typescript

### ISSUE THREAD

**Issue by abbeyperini-deque** [dequelabs/cauldron#625]
add `tabIndex?: number` to Props interface on line 16 of https://github.com/dequelabs/cauldron/blob/develop/packages/react/src/components/Code/index.tsx

**Comment by stephenmathieson** [comment]
The `<Code>` component should support all valid `<code>` props, not just `tabIndex`.

**Comment by tbusillo** [comment]
@stephenmathieson Think we should be good to close this ticket for the purposes of @abbeyperini-deque's issue, yeah? Can add in `{...props}` (or a similar convention) without a problem, just wondering if we should track via separate ticket.

**Comment by okry** [comment]
Fixed
