### ISSUE TITLE
Checkbox wrapping issue

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#627]
![checkbox with label above the visual checkbox](https://user-images.githubusercontent.com/1062039/164276980-eac78d11-90a5-4f7c-8170-37bd4b6ffc4f.png)

Checkboxes have an issue when the label needs to wrap, the label content appears before the checkbox.

**Comment by abbeyperini-deque** [comment]
Goal is to keep the label on the same line as the checkbox.

**Comment by YuriDevAT** [comment]
Hi. I would like to work on this issue.

**Comment by YuriDevAT** [comment]
Hi 🙂 I wanted to work on my open issues over the weekend but I am facing problems with yarn since then which I cannot overcome. Since I will not have time to work on it for the next few weeks, I would unassign me, and come back later if the issue is still open. Sorry for the inconvenience.

**Comment by abbeyperini-deque** [comment]
Not a problem! Thanks for all your contributions!
