### ISSUE TITLE
[Pagination] Create PageSize component

### ISSUE THREAD

**Issue by okry** [dequelabs/cauldron#630]
Axe Reports' tables use a Page Size component to handle custom page sizes for our tables. If we could, we would like to have the Page Size input to be on the same row as the main Pagination component.

To manage the rendering of this component we could probably check the existence of an `onPageSizeChange` callback? We could also position this element using Flex-Box or CSS-Grid. For resizability, we would likely stack these two elements on top of each other.

Any thoughts on a potential design for this? @awpearlm @bobbyomari

**Comment by scurker** [comment]
Not sure this is needed still.
