### ISSUE TITLE
Deprecated site shows up higher in google search

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#636]
---

# 🛑 This is not ready to be picked up 🛑 

---

# Reqs from marketing (@itsawesomeryan)

- Add Deque logo to nav (would need design team to provide details)
- Create Cauldron homepage (can probably migrate this from the old site)
- Add descriptive text to the top of each component page - explaining to the user the purpose of the component and why/how to use it. (can also be modelled off of old site)
- Add meta descriptions to each page in alignment with the descriptive text supporting it.

**Comment by awpearlm** [comment]
The old site should be stripped of all navigation and the homepage replaced with new content. We'll use new topbar, and the content can have links to cauldron resources as well as any pertinent information.

**Comment by schne324** [comment]
Or a redirect?

**Comment by awpearlm** [comment]
nevermind, just add a redirect

**Comment by abbeyperini-deque** [comment]
The redirect was added, so this issue can be closed.

**Comment by schne324** [comment]
as @abbeyperini-deque said, we've got the redirect setup already so I am closing this ticket (pattern-library.dequelabs.com)
