### ISSUE TITLE
Create new component for our 'issue view' expand/collapse widget

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#650]
<img width="462" alt="Screen Shot 2022-05-11 at 9 43 43 AM" src="https://user-images.githubusercontent.com/3180185/167903193-561c0c9a-e72f-447d-8451-e2287121b17b.png">

ping @schne324 / @scurker  for the uxpin link as an example

**Comment by stephenmathieson** [comment]
Is this just a styled version of https://github.com/dequelabs/react-wai-accordion?
