### ISSUE TITLE
Implement RFC Process

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#653]
Given that we're starting to have more teams and outside contributors making contributions to cauldron, we should consider that major new features and/or changes should follow a request for comments, or an "RFC" process. 

Some RFC Examples: 

* [React RFC](https://github.com/reactjs/rfcs)
* [VUE RFC](https://github.com/vuejs/rfcs)
* [eslint RFC](https://github.com/eslint/rfcs)

The purpose of an RFC would be to help gain consensus when there are substantial changes that would need to be made to cauldron's code and/or documentation. Hopefully the forming of an RFC process can itself be used as a test bed as to what we want our RFC process to look like. Some questions we may want to consider while forming an RFC:

* What constitutes a "substantial" change?
* When should an RFC be required/not required?
* Should there be a time limit on an RFC?
* What happens if no consensus is reached?

**Comment by scurker** [comment]
This is done:
https://github.com/dequelabs/cauldron/blob/develop/rfcs.md

**Comment by Keerthi-Penukonda** [comment]
No QA testing required for this ticket.
