### ISSUE TITLE
Add "border" variant for Table component

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#661]
![cauldron table with border variant](https://user-images.githubusercontent.com/1062039/169328364-fdbd25fc-8e1b-43d0-ad77-e992fb708098.png)

Please contact @awpearlm or @scurker or @schne324 if you need access to the UX pin.

**Comment by villet2** [comment]
I could work on this one.

**Comment by villet2** [comment]
@scurker Is there a spec for the border styles?

**Comment by scurker** [comment]
Here's some example of tables in different configurations:

<details>
  <summary>Light theme w/o header row</summary>

![cauldron light themed table](https://user-images.githubusercontent.com/1062039/196498176-b170981f-4d09-473a-86a4-f964de20146b.png)

</details>

<details>
  <summary>Light theme w/ header row</summary>

![cauldron light themed table](https://user-images.githubusercontent.com/1062039/196498210-e23f3449-1b6a-4792-935c-5f099d49f831.png)

</details>

<details>
  <summary>Dark theme w/o header row</summary>
  
![cauldron dark themed table](https://user-images.githubusercontent.com/1062039/196498338-00e85c77-cff3-44ec-83f9-8ece50cd1186.png)

</details>

<details>
  <summary>Dark theme w/header row</summary>

![cauldron dark themed table](https://user-images.githubusercontent.com/1062039/196498376-c89fb408-b883-4bb6-8f63-8632f4a93b4e.png)
</details>

The border for the light table should be `#cccccc` utilizing the css variable `var(--gray-40)`.

The border for the dark table should be `#5d676f` utilizing the css variable `var(--stroke-dark)`.

There does appear to be a drop shadow for the bordered variant, I think it may be `box-shadow: 0 2px 3px rgba(0, 0, 0, 0.15)` for both themes.

**Comment by scurker** [comment]
This has been implemented
