### ISSUE TITLE
Switch `<Icon>` components to use `span` instead of `div` for semantic HTML

### ISSUE THREAD

**Issue by anastasialanz** [dequelabs/cauldron#668]
When using an `<Icon type="external-link">` component in a `Link` component that is inside of a `<p>` tag, you will see an error for `Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.`

```
<p>
  <Trans>
    Sample Text.
    <Link
      target="_blank"
      rel="noreferrer noopener"
      className={styles.finalLink}
      href="https://github.com"
    >
      External Link <Icon type="external-link"></Icon>
    </Link>
  </Trans>
</p>
```

Since an `Icon` could be used inside of `<p>` tags in this link example, I think the safest thing to do would be to change the `div` to a `span` for the `Icon` component.

The `p` tag only accepts phrasing content. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p

This is similar to https://github.com/dequelabs/cauldron/issues/224.

**Comment by villet2** [comment]
I could work on this issue.
