### ISSUE TITLE
Look into tooltip orientation and give top orientation the priority

### ISSUE THREAD

**Issue by awpearlm** [dequelabs/cauldron#670]
It's good that tooltips adjust based on the form factor of the screen and how much space they have, however they seem to randomly move around when the screens size changes even though there's no reason they should. The logic for tooltips needs to be adjust so...

- We prioritize tooltips to _try_ and be ABOVE the object they are referring to. This is often times a (?) icon.
- The tooltip's orientation, relative to its reference, should only change if something is impeding it being show properly (i.e. it's close to the edge of the screen, the form factor changes, the screen is scrolled).

**Comment by scurker** [comment]
This can be specified by the author, if we want to have a specific initial cardinal direction, this should be called out in design.
