### ISSUE TITLE
Provide overview/description for existing components and new components moving forward

### ISSUE THREAD

**Issue by tbusillo** [dequelabs/cauldron#672]
As it stands right now, some of the existing components have descriptions (e.g., what the component is, what it is for, when to use it, etc.). However, many are missing descriptions and there is no general rule that requires descriptions for new components. 

This issue is to cover two things:
- Update [contributing guidelines](https://github.com/dequelabs/cauldron/blob/develop/CONTRIBUTING.md) to include new components having a description that covers: 1) what the component is, 2) what it is used for, 3) and when to use it.
- Update existing components to include the same description described above. 

Ping me for additional details/information as to the "why" if interested.

**Comment by abbeyperini-deque** [comment]
Component descriptions have been added to all existing pages and another issue opened about [making them more useful ](https://github.com/dequelabs/cauldron/issues/763) and adding when to use/when not to use sections. To close this, contributing guidelines just need to be updated.

**Comment by tbusillo** [comment]
@abbeyperini-deque This may be able to be closed without updating the contributing guidelines. I believe there was some discussion previously about whether it made sense to make this a requirement in the guidelines, as there was some concern that blocking a PR due to missing a description may be overboard. 

@scurker do you happen to remember what the consensus was on the above?

**Comment by scurker** [comment]
I believe all the pages should have component descriptions (v1 and v2), I can be sure this happens for new documentation going forward.
