### ISSUE TITLE
Code component uses inline styles making it impossible to override anything

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#72]

**Comment by stephenmathieson** [comment]
I think the idea is you pass `react-syntax-highlighter` a [`theme`](https://github.com/dequelabs/cauldron/blob/develop/packages/react/src/components/Code/index.tsx#L13) to override styles.

**Comment by stephenmathieson** [comment]
Looks like we can pass `useInlineStyles={false}` and provide our own stylesheet if we want. See https://github.com/react-syntax-highlighter/react-syntax-highlighter#javascript-styles.
