### ISSUE TITLE
Opt-in to Hacktoberfest

### ISSUE THREAD

**Issue by abbeyperini-deque** [dequelabs/cauldron#759]
Add the “hacktoberfest” topic to your repository to OPT-IN TO HACKTOBERFEST and indicate you’re looking for contributions.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by schne324** [comment]
Done:

<img width="414" alt="hacktoberfest topic under 'About' section for cauldron repo" src="https://user-images.githubusercontent.com/3180185/189959712-066be9e1-bbaf-4a19-9323-1711e2bed963.png">
