### ISSUE TITLE
Component Description Improvements

### ISSUE THREAD

**Issue by karnett** [dequelabs/cauldron#763]
On the doc pages for each component, we want to improve the existing component descriptions.

From feedback on #756 
We want to highlight the 'how/when/why' for each component.

Conversation:
https://github.com/dequelabs/cauldron/pull/756#pullrequestreview-1106324585

**Comment by abbeyperini-deque** [comment]
Example: https://carbondesignsystem.com/components/checkbox/usage/

**Comment by scurker** [comment]
I think our documentation as a whole needs a facelift, I think the example that @abbeyperini-deque provided is a good start but it would be great to define a minimum definition of what we need for each component.
