### ISSUE TITLE
Update Demo component to work with nested, complicated components

### ISSUE THREAD

**Issue by abbeyperini-deque** [dequelabs/cauldron#764]
Pages not using the Demo component:

- Accordion
- Alert
- Breadcrumb
- ExpandCollapsePanel
- Layout
- Modal
- NavBar
- OptionsMenu
- Pointout
- Table
- Tabs
- TopBar
- TopBarMenu
- TwoColumnPanel

**Comment by scurker** [comment]
Leaving this in the backlog for now, I'd like to figure out how we can more easily improve documentation without having to write a bespoke component to do so. I'd like to dig in further to see how other design systems / pattern libraries solve this problem.

**Comment by scurker** [comment]
With the V2 docs, we will no longer be using the `Demo` component but rather write content using mdx/code fences that will handle this correctly.
