### ISSUE TITLE
Alert demo page: triggers overlap at reflow.

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#769]
## Description
Content overlaps other content at reflow.
Note: For reflow, resize the browser viewport to 640px width by 512px height and zoom in to 200%

## Element: 
-Default Alert 
-Warning Alert

**Location**: Below Demo

**Note**: Button overlaps at the reflow checkpoint
Recommendation to fix
**RULE**: Content MUST be presented without loss of information or functionality when the viewport is set to 320 CSS pixels wide.

## HOW TO FIX: 
Fix this issue by ensuring content does not overlap other content when the screen width is set to 320px by using techniques such as CSS media queries, grids, or flexbox to reflow content down to 320px width.

## REFERENCE: 
Deque University:https://dequeuniversity.com/class/responsive-zoom2/zoom/linear-text-reflow
https://dequeuniversity.com/class/responsive-zoom2/responsive/
WCAG Understanding document:
https://www.w3.org/WAI/WCAG21/Understanding/reflow

## BACKGROUND: 
People with low vision often read content on a desktop computer by scaling content using the browser zoom - up to 400%. When zooming causes content to overlap other content, users with low vision may not be able to see or use that content. When content is created so that it reflows without losing information or functionality at screen widths down to 320px, users can view a web page in a 1280px width browser screen and zoom the content to 400% (320px) without having to scroll side to side to read and without losing access to content.

**selector**: #main-content > div > button:nth-child(3)
**source**: 

```html
<button type="button" class="Button--primary">Default Alert</button>
```

**Comment by anastasialanz** [comment]
Is this issue a duplicate of https://github.com/dequelabs/cauldron/issues/580?
