### ISSUE TITLE
Align external link icon with the baseline of the link

### ISSUE THREAD

**Issue by anastasialanz** [dequelabs/cauldron#776]
On the [Cauldron](https://cauldron.dequelabs.com/) homepage and footer, there are several external links with external icons. To make these look a bit better, let's align the external icon with the baseline of the link.

<img width="1512" alt="Screen Shot 2022-09-16 at 1 33 38 PM" src="https://user-images.githubusercontent.com/3081483/190716796-30bbbefa-ed3c-41de-8390-6bbb379a358f.png">

Baseline alignment examples from https://axe.deque.com/:
<img width="321" alt="Screen Shot 2022-09-16 at 1 25 26 PM" src="https://user-images.githubusercontent.com/3081483/190716370-6d163857-f990-471f-b138-5e10d4917334.png">
<img width="272" alt="Screen Shot 2022-09-16 at 1 24 30 PM" src="https://user-images.githubusercontent.com/3081483/190716375-f809134e-9d7b-4de3-b71c-595285ae97f5.png">

PR https://github.com/dequelabs/cauldron/pull/746 introduced external links to the homepage and footer.

**Comment by lmas3009** [comment]
Can i work on this

**Comment by anastasialanz** [comment]
@lmas3009 yes, go for it!

**Comment by scurker** [comment]
This should be addressed by #869 when we consolidate all the icons.
