### ISSUE TITLE
Add Demo component to ClickOutsideListener docs page

### ISSUE THREAD

**Issue by abbeyperini-deque** [dequelabs/cauldron#783]
Update [ClickOutsideListener](https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/ClickOutsideListener/index.js) to use the Demo component ([example](https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/Button/index.js)) instead of duplicating HTML.

**Comment by rafaelaqueirozg** [comment]
Hey @abbeyperini-deque, how's it going?

Can you please assigne me to this issue? I've just opened a pull request to solve this.

**Comment by scurker** [comment]
This is no longer needed as V2 documentation does not use the demo component.
