### ISSUE TITLE
Add Demo component to ProgressBar docs page

### ISSUE THREAD

**Issue by abbeyperini-deque** [dequelabs/cauldron#784]
Update [ProgressBar docs page](https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/ProgressBar/index.js) to use the Demo component ([example](https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/Button/index.js)) instead of duplicating HTML.

**Comment by krosenk729** [comment]
Hey! I would love to take this one for hacktober fest 😄🎃
