### ISSUE TITLE
Github logo gets cut off in topbar at 200% zoom

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#788]
![image](https://user-images.githubusercontent.com/3180185/191362951-9cce4f37-d2fd-46a4-940f-22248ccbbee1.png)

TBD: how should the topbar be adapted at such small viewports? I'd assume we could remove the text "Cauldron" and continue to have the logo rendered.... @awpearlm thoughts?

**Comment by abbeyperini-deque** [comment]
Duplicate issue. Fixed in PR 808.
