### ISSUE TITLE
Bug: command missing in readme.md 

### ISSUE THREAD

**Issue by YuriDevAT** [dequelabs/cauldron#796]
### Steps to reproduce

In the readme.md file, in the development section, there is no command under "install dependencies".

<img width="502" alt="Missing command on how to install dependecies." src="https://user-images.githubusercontent.com/54622834/194131528-e1c9c5f9-eb87-458a-ae33-e5ec6f1a2015.png">

I assume it should be:

`$ yarn i`

or 

`$ yarn install`

### Expected Behavior

To see a command on how to install dependencies.

### Actual Behavior

No command written on how to install dependencies.

### Version

4.7.0

### Anything else we should know?

Additional information

**Comment by utkarsh1311** [comment]
Hey Yuri. I believe that `yarn` command is equivalent to `npm i` or `npm install`. You can also use `yarn install`. 
I do believe that `yarn install` will be a better choice for the installation instructions as it is more self explanatory.

**Comment by anastasialanz** [comment]
@YuriDevAT Running `yarn` does the same thing as`yarn install`.

https://classic.yarnpkg.com/lang/en/docs/cli/#toc-default-command

> Running yarn with no command will run yarn install, passing through any provided flags.

**Comment by YuriDevAT** [comment]
Thanks for your comments.
