### ISSUE TITLE
Props table for OptionsMenu component docs page

### ISSUE THREAD

**Issue by abbeyperini-deque** [dequelabs/cauldron#805]
Add a [PropDocs component](https://github.com/dequelabs/cauldron/blob/develop/docs/Demo/PropDocs.js) at the bottom of the [OptionsMenu component docs page](https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/OptionsMenu/index.js) with the [OptionsMenu component props](https://github.com/dequelabs/cauldron/blob/dcc3921f2bae7576de0c594738436eacb7ad20a0/packages/react/src/components/OptionsMenu/OptionsMenu.tsx#L49).

[Example page](https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/Breadcrumb/index.js)
[Example page with props that aren't `children` or `className`](https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/ProgressBar/index.js)

**Comment by VedanthB** [comment]
Hi , I would like to work on this

**Comment by VedanthB** [comment]
Hi @abbeyperini-deque I have raised a PR, please review it.

**Comment by scurker** [comment]
Outdated issue, this has documentation. Closing.
