### ISSUE TITLE
Props table for TopBar component docs page

### ISSUE THREAD

**Issue by abbeyperini-deque** [dequelabs/cauldron#806]
Add a [PropDocs component](https://github.com/dequelabs/cauldron/blob/develop/docs/Demo/PropDocs.js) at the bottom of the [TopBar component docs page](https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/TopBar/index.js) with the [TopBar component props](https://github.com/dequelabs/cauldron/blob/dcc3921f2bae7576de0c594738436eacb7ad20a0/packages/react/src/components/TopBar/TopBar.tsx#L9).

[Example page](https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/Breadcrumb/index.js)

**Comment by Ananyamadhu08** [comment]
Hey, I would like to work on this.

**Comment by Ananyamadhu08** [comment]
@abbeyperini-deque have created a pull request please review.
