### ISSUE TITLE
Props table for TopBarMenu component docs page

### ISSUE THREAD

**Issue by abbeyperini-deque** [dequelabs/cauldron#807]
Add a [PropDocs component](https://github.com/dequelabs/cauldron/blob/develop/docs/Demo/PropDocs.js) at the bottom of the [TopBarMenu component docs page](https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/TopBarMenu/index.js) with the [TopBarMenu component props](https://github.com/dequelabs/cauldron/blob/dcc3921f2bae7576de0c594738436eacb7ad20a0/packages/react/src/components/TopBar/TopBarMenu.tsx#L32).

[Example page](https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/Breadcrumb/index.js)
[Example page with props that aren't `children` or `className`](https://github.com/dequelabs/cauldron/blob/develop/docs/patterns/components/ProgressBar/index.js)

**Comment by logicalahara** [comment]
Hey @abbeyperini-deque, I would love to contribute to this issue.
### Will you please assign this to me ?

**Comment by scurker** [comment]
Outdated issue, props are current documented for `TopBarMenu`. Closing.
