### ISSUE TITLE
Unify how refs are described in prop tables

### ISSUE THREAD

**Issue by abbeyperini-deque** [dequelabs/cauldron#819]
Ref is currently in these prop tables:
- [Modal](https://github.com/dequelabs/cauldron/pull/815)
- [Alert](https://github.com/dequelabs/cauldron/blob/ded5fdafa720d19cc47b2e7b51f61437a37a3e6b/docs/patterns/components/Alert/index.js#L152)
- [Button](https://github.com/dequelabs/cauldron/blob/fa8e54c533a55ae2c5164802675a6a3fbf8fa985/docs/patterns/components/Button/index.js#L74-L77)
- [Link](https://github.com/dequelabs/cauldron/blob/fa8e54c533a55ae2c5164802675a6a3fbf8fa985/docs/patterns/components/Link/index.js#L32-L44)
- [LoaderOverlay](https://github.com/dequelabs/cauldron/blob/fa8e54c533a55ae2c5164802675a6a3fbf8fa985/docs/patterns/components/LoaderOverlay/index.js#L55-L58)
- [TextField](https://github.com/dequelabs/cauldron/blob/fa8e54c533a55ae2c5164802675a6a3fbf8fa985/docs/patterns/components/TextField/index.js#L86-L88)
- [Toast](https://github.com/dequelabs/cauldron/blob/fa8e54c533a55ae2c5164802675a6a3fbf8fa985/docs/patterns/components/Toast/index.js#L173-L177)
- [OptionsMenu](https://github.com/dequelabs/cauldron/pull/809)

**Comment by scurker** [comment]
The V2 docs should handle this, for `<ComponentProps>` you can pass in a `refType` that has a consistent description.
