### ISSUE TITLE
Update dark theme's focus ring color

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#827]
Update it to `#F5A4FF`

1. The focus on the dark theme needs to be changed to #F5A4FF. This will be almost indistinguishable to most folks eyes when it changes.
1. Here is how the new color will stack up against the backgrounds we design against: 
<img width="553" alt="image" src="https://user-images.githubusercontent.com/5720243/187700324-bab4f77f-3767-4f01-8346-a5a04b230497.png">

**Comment by scurker** [comment]
This would be updating the `--focus-dark` variable.
