### ISSUE TITLE
RFC: Add Non-Dialog Alert Component

### ISSUE THREAD

**Issue by tbusillo** [dequelabs/cauldron#831]
As it stands, there is no component in Cauldron that fits the traditional `<Alert>` paradigm. For internal purposes, reference this thread in slack: https://deque.slack.com/archives/G017VP5SCUB/p1668810189855009. 

## Potential Ideas
- Create a new component with a new naming convention (e.g., `<Callout>`)
- Deprecate the existing `<Alert>` and change its name to `<AlertDialog>` and use `<Alert>` for new component)
- Deprecate the existing `<Alert>`, `<Modal>`, and possibly other components and use `forceAction` to infer the type of component to use (e.g., dialog vs. modal vs. alert). 
- See: existing styles used in [Gatsby docs](https://github.com/dequelabs/product-docs-site/blob/8f682fd5d7740b727039eceb131eb709473489e6/plugins/gatsby-remark-callout/index.scss)

Note: aside from the first option, there will likely be a breaking change in whichever approach we choose. 

## Examples

![image](https://user-images.githubusercontent.com/1016306/203335065-8ba680f1-6ec7-4375-a98c-4102aebe279c.png)
_source: https://docs.deque.com/devtools-html/4.0.0/en/welcome-axe-devtools_

- [Bootstrap's Alert Component(s)](https://getbootstrap.com/docs/4.0/components/alerts/)

**Comment by scurker** [comment]
This is effectively #1136, so we can close this issue.
