### ISSUE TITLE
link as a thin and primary button has incorrect padding and font weight

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/cauldron#845]
### Steps to reproduce

Steps to reproduce

```html
<a href="#" class="Button--primary Button--thin">
  Hello
</a>
```

### Expected Behavior

It has the correct padding and font weight.

### Actual Behavior

It doesn't have the correct padding and font weight,

### Version

latest/next

### Anything else we should know?

**Expected**

<img width="265" alt="image" src="https://user-images.githubusercontent.com/571265/211578950-686c2119-2061-4b15-9573-4adb2502d5cc.png">

**Actual**

<img width="241" alt="image" src="https://user-images.githubusercontent.com/571265/211579018-98191999-ca85-4e1e-97e5-4ddae214a9f9.png">

**Comment by gayathrit12** [comment]
This is not working as expected. So, reopening it.

## Screenshot:
![image](https://user-images.githubusercontent.com/102580833/212324914-9cea2a8a-ce41-49b0-96c2-38eb113c22e4.png)

**Comment by dequejenn** [comment]
@gayathrit12 - I just found out when something is updated in Cauldron it needs additional steps before the change shows up in walnut. To QA, just check it in Cauldron with this link: https://cauldron.dequelabs.com/components/Link

We will have then Projects Page issue checked during the Design Approval to ensure the Cauldron changes came through to the Projects page, so you don't need to worry about it.

**Comment by gayathrit12** [comment]
## Retesting details:
Working as expected.

## Screenshots:
![image](https://user-images.githubusercontent.com/102580833/213140558-53cac2f3-1f9a-42a9-ac81-63a4e8808daa.png)

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Server URL**                | _https://axe.dequelabs.com/_ |
| **Server version**           | _4.62.0_ |
| **OS**                              | _Windows 10_ |
| **Tested Browsers**       | _Chrome Version 108.0.5359.125 (Official Build) (64-bit)_ |

**Comment by gayathrit12** [comment]
Reopening this ticket as the button name is not matching with the UX Pin.

## UX Pin: "Add New project" 
![image](https://user-images.githubusercontent.com/102580833/213174191-fc8ac8fe-085a-4c52-abb8-c00c8573eab7.png)

## Web App:  "Add a new project" 
![image](https://user-images.githubusercontent.com/102580833/213174272-b2a03dc9-90eb-4785-a4ed-0e8b0bfd0bc9.png)

**Comment by stephenmathieson** [comment]
@gayathrit12 this is no longer an issue with Cauldron. The button/link styles are working correctly.
