### ISSUE TITLE
Bug: two <IconButton>s inline have strange margins/spacing

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/cauldron#846]
### Steps to reproduce

Steps to reproduce

```js
<div>
  <IconButton icon="copy" label="Copy" />
  <IconButton icon="eye" label="View" as={Link} to="#" />
</div>
```

### Expected Behavior

Not a bug. They should be correctly aligned with one another.

<img width="202" alt="image" src="https://user-images.githubusercontent.com/571265/211612467-d8fcc7fc-c83c-4488-83e5-bfb3b2f2234d.png">

### Actual Behavior

A bug happened! They're not aligned with one another.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/571265/211612413-fa5cc82a-0315-4954-8913-5da0038a928f.png">

### Version

latest/next

### Anything else we should know?

Additional information

**Comment by gayathrit12** [comment]
This is working as expected.

## Screenshot:
![image](https://user-images.githubusercontent.com/102580833/213140899-9c105b8b-7a4b-4e27-837d-9f9ccb9e900d.png)
![image](https://user-images.githubusercontent.com/102580833/213140983-4329bbdc-6cc1-4d0d-8a7c-89954f665132.png)

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Server URL**                | _https://axe.dequelabs.com/_ |
| **Server version**           | _4.62.0_ |
| **OS**                              | _Windows 10_ |
| **Tested Browsers**       | _Chrome Version 108.0.5359.125 (Official Build) (64-bit)_ |
