### ISSUE TITLE
Bug: Two column panel with Code on 320px does not wrap as intended 

### ISSUE THREAD

**Issue by Zidious** [dequelabs/cauldron#857]
### Steps to reproduce

Using the sample code from the `<TwoColumnPanel />` and a test html snippet: 

```jsx
  <TwoColumnPanel>
        <ColumnLeft aria-labelledby="sidebar">
          <ColumnHeader id="sidebar">Items</ColumnHeader>
          <nav aria-label="Sidebar navigation">
            <ul>
              <li>
                <a href="#section-1">Section 1</a>
              </li>
            </ul>
          </nav>
        </ColumnLeft>
        <ColumnRight aria-labelledby="item-header">
          <ColumnHeader id="item-header">test</ColumnHeader>
          <div>
            <Code language="html">
              {`<a target="_blank" href="http://elementalselenium.com/">Elemental Selenium</a>`}
            </Code>
          </div>
        </ColumnRight>
 </TwoColumnPanel>
```

### Expected Behavior

1. Option to wrap code snippet on smaller view ports
2. Should be horizontally scrollable if overflow X exceeds the width 

### Actual Behavior

Code block is neither wrapped or scrollable: 

<img width="379" alt="image" src="https://user-images.githubusercontent.com/41127686/213729185-13571afb-cc33-4160-aecf-ee71e706cf73.png">

### Version

4.7

### What browsers are you experiencing the problem on?

Chrome

### Relevant log output

```shell
NA
```

### Anything else we should know?

NA

**Comment by Zidious** [comment]
Fixing this in Cauldron would have unintended side effects. If you come across this use case, you can apply the following: 

```css
.TwoColumnPanel__Right {
/* allows `<Code />` to correctly have scrollable content */
overflow: hidden
}

```

**Comment by gayathrit12** [comment]
Per Gabe, no QA required.
