### ISSUE TITLE
Add new "share-nodes" icon

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#879]
![share-nodes-solid](https://user-images.githubusercontent.com/3180185/215903140-3a180cd3-a21c-4d14-84aa-0a97760d47ac.svg)

```
<Icon type="share-nodes" />
```

NOTE: if you want to come up with a better name, go for it!

**Comment by bobbyomari** [comment]
I would call it whatever Font Awesome calls it, which is `share-nodes` so it's easy to find in the future.

**Comment by Keerthi-Penukonda** [comment]
Added "share-nodes" icon successfully in cauldron.
![image](https://user-images.githubusercontent.com/40262884/218977998-0957c417-2292-4349-b33f-d87afc0b23a2.png)
