### ISSUE TITLE
missing bg color for default selected/sorted table header

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/cauldron#883]
When a sortable table header is selected by default, the highlighted background color is not applied.

For example, in the Watcher projects page, we sort projects by "Last Run" by default:

<img width="1144" alt="color missing from 'last run' column" src="https://user-images.githubusercontent.com/571265/216646375-dd3133a3-2b34-4bfc-bf96-eadc06f380fe.png">

**Comment by anastasialanz** [comment]
This appears to be fixed. @stephenmathieson Is it fixed on your end?

**Comment by stephenmathieson** [comment]
It appears that _you_ fixed this, @anastasialanz 😉

**Comment by anastasialanz** [comment]
> It appears that _you_ fixed this, [@anastasialanz](https://github.com/anastasialanz) 😉

Oh! I thought I fixed a different issue!
