### ISSUE TITLE
Change Link Hover Color in Light Mode

### ISSUE THREAD

**Issue by tbusillo** [dequelabs/cauldron#886]
## Summary
- Change the `Link` component's default hover styling in order to improve contrast when it is used on light dark backgrounds. 
- Solution: Replace `--link-text-color-hover` use of `var(--accent-primary)`  with a new variable using `#3873A3`. 

see: https://github.com/dequelabs/cauldron/blob/4bf529af4b414bea0780cdaf70c3ff8597a82a97/packages/styles/link.css#L3

**Comment by Keerthi-Penukonda** [comment]
This issue is fixed.

![image](https://user-images.githubusercontent.com/40262884/218959360-c5d70719-1226-4769-8786-c51de3773086.png)
