### ISSUE TITLE
Bug: ExpandCollapse component should use font-family: roboto

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/cauldron#888]
### Steps to reproduce

https://cauldron.dequelabs.com/components/ExpandCollapsePanel is not forcing all font within it to be `font-family: roboto`

### Expected Behavior

All font should be `font-family: roboto`

### Actual Behavior

It is not the right font

### Version

I dunno

### Anything else we should know?

Additional information

**Comment by Bracciata** [comment]
Hope you don't mind me tackling this one! I was able to replicate and implement a fix in the mentioned PR.

**Comment by scurker** [comment]
This is related to not having a css reset (#18) since the button is inheriting whatever is set via the user agent stylesheet.

**Comment by bobbyomari** [comment]
Let's add `font-weight: 500` (variable) to all buttons as well so it does not inherit from the browser.

**Comment by Bracciata** [comment]
Correct me if I am wrong but wouldn't adding a CSS reset make the buttons also inherit `font-weight: 500` @bobbyomari ?

**Comment by scurker** [comment]
We want to add a css reset eventually, but for now we're going to override the font-family/weight for just buttons.

**Comment by Bracciata** [comment]
Makes sense! Added it.
