### ISSUE TITLE
Create a FileInput Component

### ISSUE THREAD

**Issue by Bracciata** [dequelabs/cauldron#898]
One of the projects I am working on uses a File Input and it does not seem to currently be an option within Cauldron.

**Comment by scurker** [comment]
We should be able to use a button (with maybe `type="file"`) under the hood and append the uploaded items on the page. Here's an example:

![file upload button](https://user-images.githubusercontent.com/1062039/221962683-dfa0e4c0-72c7-48cc-898f-a525bb92331c.png)
