### ISSUE TITLE
Keyboard focus order is not logical

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#910]
https://axeauditor.dequecloud.com/test-run/f6620faa-6d1e-11ec-a0b7-97f3ccf70959/issue/176820ac-77bc-11ec-b6a5-678c9565e34a?sortField=identifier&sortDir=asc&page=0&activeTab=dt-issue&pageSize=50&viewMode=issues&row=21&issuesCount%5B0%5D=&issuesCount%5B1%5D=&filter%5Bgroup_id%5D%5B0%5D=42b8f3a2-ac6e-11ed-adb1-3bfa602e0928&filter%5Bgroup_id%5D%5B1%5D=df2b20c0-1317-11ed-acb1-c7cbc98656eb

## Description
Keyboard focus order is not logical in such a way that it affects the meaning or operability of the content.
Focus jump to the cauldron element present in the header after selecting active controls on the below pages - 
1. Select > Do you like yogurt > Maybe, No, yes items
2. Point Out 
3. Pagination 
4. Nav Bar (On activating the "Toggle between mobile and non-mobile mode, Main menu" using the keyboard)
5. Checkbox (On activating the checkbox using the space bar)
6. Radio Group (At radio buttons, while using arrow keys to navigate between them)
7. Description List (On activating the checkbox using the space bar)
8) Accordion ( After activating the accordion expand/ collapse section)
9)Progress bar ( After activating the " Show Animated Progress" button)
10)Table (After activating the sort option in the sortable table)

Notes: 
1. The above-mentioned behavior is using the keyboard without a screen reader.
2. Also, there is some inconsistency in this behavior using different laptop devices. 
3. In some systems, the checkboxes and radio buttons seem to be working fine.
But it is consistently not working in some systems.
### RULE : 
The reading and navigation order MUST be logical and intuitive.

### HOW TO FIX: 
Fix this issue by ensuring the DOM order is logical so that the focus order will naturally follow. Do not use positive tabindex values to "correct" the tab order as it will not change the reading order for screen reader users and will almost always cause unintended, significant problems.

### REFERENCE: 
Deque University: https://dequeuniversity.com/class/input-methods2/keyboard-input/tab-order

### BACKGROUND: 
When keyboard focusable components do not receive focus in a logical order, people with mobility impairments, reading disabilities, and low vision are all impacted. The keyboard focus order must be logical and consistent with the layout of the content. (Note: This does not mean that the focus order has to be identical to the visual order, as long as the user can still understand and operate the content.) A logical focus order makes interaction with content predictable for people who rely on a keyboard to interact with a web content.

**Comment by scurker** [comment]
We need to investigate these issues. I was able to replicate some odd behavior with the `Select` component. The active element does appear to jump around when an option is selected, so there may be odd behavior elsewhere as well.

**Comment by VaniChinnam** [comment]
This is similar to #790. The issue is observed only when the extension axe auditor v3.0.3 is enabled.
By default is working fine. In auditor changed it to best practice. Will update VPAT.
@schne324 @scurker

**Comment by scurker** [comment]
We've rewritten documentation since this issue was first opened. This issue appears to no longer be valid.
