### ISSUE TITLE
Color contrast issue with codeblock orange color on light theme

### ISSUE THREAD

**Issue by bobbyomari** [dequelabs/cauldron#930]
### The orange used here does not pass color contrast. 

![image](https://user-images.githubusercontent.com/28606186/222794182-de015672-2fdf-491c-99b2-96751bd09195.png)

![image](https://user-images.githubusercontent.com/28606186/222794432-350bda08-aa21-4437-b30c-f329282b5911.png)

**Comment by scurker** [comment]
Update the following colors:

## Light Theme

* `#969896` → `#666666`
* `#f9915 ` → `#8a3500`
* `#dc322f` → `#c92e40`
* `#969896` → `#666666`

## Dark Theme

* `var(--accent-primary-active)` → `#79A7D9`
