### ISSUE TITLE
Filters Toolbar

### ISSUE THREAD

**Issue by bobbyomari** [dequelabs/cauldron#931]
# Intro
The Filters toolbar is currently being implemented across multiple products in multiple ways by multiple teams. I am proposing we create a standardized Cauldron component that developers can insert and customize as needed for their projects.

# Variations

1. **Basic Filters Toolbar** – this variation is a single row that includes a filter label, filter tags, filter button, and export button
2. **Advanced Filter Toolbar** – this variation is a double row that is usually used where a bulk selection is required. This will show the items mentioned above in addition to # of items found, # of items selected, bulk actions with Apply button. 

# Components used

- Panel
- Tags
- Form inputs
- Buttons

# Designs
The image below shows a "fully loaded" filter toolbar from axe Monitor.
![image](https://github.com/dequelabs/cauldron/assets/28606186/ba4d8898-3b44-493c-9c3a-2bb0a1f30108)

**Comment by scurker** [comment]
Ideally, this would be a documentation of different patterns that we use across Deque and showing some examples of the composition of components needed to achieve that pattern.

**Comment by scurker** [comment]
It's unlikely this is a good candidate for Cauldron, so closing.
