### ISSUE TITLE
Sync checkboxes with UXpin

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#949]
[Pattern Library](https://preview.uxpin.com/520e80315786a67ba43a3ca50598e6d69782627c#/pages/161871161/simulate/no-panels?mode=i)
[Checkbox UXPin](https://preview.uxpin.com/design-system/c933c74928e2195cc540/6764519,light-form-checkbox-regular)

![image](https://user-images.githubusercontent.com/1062039/225104930-76c636fa-e951-438f-85b0-593d40788f53.png)

The style appears to be mostly the same, we need to update the icon (which may depend on #869) and the following:

- Focus state (slight glow)
- Active state
- Disabled state
- Font weight to label

**Comment by scurker** [comment]
For now when this gets initially implemented, ignore the icon changes and keep this issue open.

**Comment by yhafez** [comment]
Implemented focus state (without slight glow), active state, disabled state, and font weight on label, as well as other refactors and styles. Pending UI for focus state glow and icons.

**Comment by scurker** [comment]
Solution here might be similar to radio for the remaining fixes: see https://github.com/dequelabs/cauldron/issues/1034#issuecomment-1745444943

**Comment by scurker** [comment]
Not doing this anymore. Thanks @bobbyomari
