### ISSUE TITLE
Update Panel component

### ISSUE THREAD

**Issue by scurker** [dequelabs/cauldron#987]
We want to support 2 new primitive components to use as composition inside of the existing `<Panel>` component:

`Panel` should support `padding={false}` to render with no padding.

* `PanelHeader` - this would be in addition to the existing "heading" property, you shouldn't use both at the same time.

![image](https://user-images.githubusercontent.com/1062039/227268110-b3c2e6d5-537e-425c-96a7-004185cc753c.png)

* `PanelContent` - content sections that when stacked would have an adjacent border between them

![image](https://user-images.githubusercontent.com/1062039/227268884-46d285ff-f496-410f-9715-e4229947b3a3.png)

The author should also be able disable the padding for the panel content for more advanced layouts.

```
<PanelContent padding={false} />
```

For the existing heading prop, it should match the style of the `PanelHeader` with a border divider below the heading.

Note: We should enhance the documentation showing different examples of usages with both simple and more complex usages, with a note that both the `heading` prop and `PanelHeader` child should not both be used.

Related #712

**Comment by Amandeque** [comment]
Estimates: Small

**Comment by Keerthi-Penukonda** [comment]
@tbusillo can you please provide some QA notes to test this ticket?

**Comment by tbusillo** [comment]
> @tbusillo can you please provide some QA notes to test this ticket?

Hey Keerthi, I had just moved this to our board for tracking purposes last sprint. I think between Jason's review and design review with Shawn we can just QA once the updated component is implemented in some of the upcoming tickets we have. 

Will remove pull this off the board unless there's any objections!
